//!
//! TDLib `file` domain types.
//!
//! Types, enums, and functions for local and remote files, photos, audio, videos, and documents.
//!

#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};

/// Represents a local file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LocalFile {
    /// Local path to the locally available file part; may be empty
    pub path: String,
    /// True, if it is possible to download or generate the file
    pub can_be_downloaded: bool,
    /// True, if the file can be deleted
    pub can_be_deleted: bool,
    /// True, if the file is currently being downloaded (or a local copy is being generated by some other means)
    pub is_downloading_active: bool,
    /// True, if the local copy is fully available
    pub is_downloading_completed: bool,
    /// Download will be started from this offset. downloaded_prefix_size is calculated from this offset
    pub download_offset: i64,
    /// If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix in bytes
    pub downloaded_prefix_size: i64,
    /// Total downloaded file size, in bytes. Can be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage
    pub downloaded_size: i64,
}

/// Represents a remote file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct RemoteFile {
    /// Remote file identifier; may be empty. Can be used by the current user across application restarts or even from other devices. Uniquely identifies a file, but a file can have a lot of different valid identifiers.
    /// If the identifier starts with "http:" or "https:", it represents the HTTP URL of the file. TDLib is currently unable to download files if only their URL is known.
    /// If downloadFile/addFileToDownloads is called on such a file or if it is sent to a secret chat, TDLib starts a file generation process by sending updateFileGenerationStart to the application with the HTTP URL in the original_path and "#url#" as the conversion string.
    /// Application must generate the file by downloading it to the specified location
    pub id: String,
    /// Unique file identifier; may be empty if unknown. The unique file identifier which is the same for the same file even for different users and is persistent over time
    pub unique_id: String,
    /// True, if the file is currently being uploaded (or a remote copy is being generated by some other means)
    pub is_uploading_active: bool,
    /// True, if a remote copy is fully available
    pub is_uploading_completed: bool,
    /// Size of the remote available part of the file, in bytes; 0 if unknown
    pub uploaded_size: i64,
}

/// Represents a file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct File {
    /// Unique file identifier
    pub id: i32,
    /// File size, in bytes; 0 if unknown
    pub size: i64,
    /// Approximate file size in bytes in case the exact file size is unknown. Can be used to show download/upload progress
    pub expected_size: i64,
    /// Information about the local copy of the file
    pub local: crate::types::LocalFile,
    /// Information about the remote copy of the file
    pub remote: crate::types::RemoteFile,
}

/// A file defined by its unique identifier
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputFileId {
    /// Unique file identifier
    pub id: i32,
}

/// A file defined by its remote identifier. The remote identifier is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib.
/// For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputFileRemote {
    /// Remote file identifier
    pub id: String,
}

/// A file defined by a local path
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputFileLocal {
    /// Local path to the file
    pub path: String,
}

/// A file generated by the application. The application must handle updates updateFileGenerationStart and updateFileGenerationStop to generate the file when asked by TDLib
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputFileGenerated {
    /// Local path to a file from which the file is generated. The path doesn't have to be a valid path and is used by TDLib only to detect name and MIME type of the generated file
    pub original_path: String,
    /// String specifying the conversion applied to the original file; must be persistent across application restarts. Conversions beginning with '#' are reserved for internal TDLib usage
    pub conversion: String,
    /// Expected size of the generated file, in bytes; pass 0 if unknown
    pub expected_size: i64,
}

/// Describes an image in JPEG format
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PhotoSize {
    /// Image type (see https:core.telegram.org/constructor/photoSize)
    #[serde(rename = "type")]
    pub r#type: String,
    /// Information about the image file
    pub photo: crate::types::File,
    /// Image width
    pub width: i32,
    /// Image height
    pub height: i32,
    /// Sizes of progressive JPEG file prefixes, which can be used to preliminarily show the image; in bytes
    pub progressive_sizes: Vec<i32>,
}

/// Thumbnail image of a very poor quality and low resolution
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct Minithumbnail {
    /// Thumbnail width, usually doesn't exceed 40
    pub width: i32,
    /// Thumbnail height, usually doesn't exceed 40
    pub height: i32,
    /// The thumbnail in JPEG format
    pub data: String,
}

/// The thumbnail is in JPEG format
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatJpeg {
}

/// The thumbnail is in static GIF format. It will be used only for some bot inline query results
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatGif {
}

/// The thumbnail is in MPEG4 format. It will be used only for some animations and videos
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatMpeg4 {
}

/// The thumbnail is in PNG format. It will be used only for background patterns
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatPng {
}

/// The thumbnail is in TGS format. It will be used only for sticker sets
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatTgs {
}

/// The thumbnail is in WEBM format. It will be used only for sticker sets
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatWebm {
}

/// The thumbnail is in WEBP format. It will be used only for some stickers and sticker sets
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ThumbnailFormatWebp {
}

/// Represents a thumbnail
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Thumbnail {
    /// Thumbnail format
    pub format: crate::enums::ThumbnailFormat,
    /// Thumbnail width
    pub width: i32,
    /// Thumbnail height
    pub height: i32,
    /// The thumbnail
    pub file: crate::types::File,
}

/// Describes an animation file. The animation must be encoded in GIF or MPEG4 format
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Animation {
    /// Duration of the animation, in seconds; as defined by the sender
    pub duration: i32,
    /// Width of the animation
    pub width: i32,
    /// Height of the animation
    pub height: i32,
    /// Original name of the file; as defined by the sender
    pub file_name: String,
    /// MIME type of the file, usually "image/gif" or "video/mp4"
    pub mime_type: String,
    /// True, if stickers were added to the animation. The list of corresponding sticker sets can be received using getAttachedStickerSets
    pub has_stickers: bool,
    /// Animation minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// Animation thumbnail in JPEG or MPEG4 format; may be null
    pub thumbnail: Option<crate::types::Thumbnail>,
    /// File containing the animation
    pub animation: crate::types::File,
}

/// Describes an audio file. Audio is usually in MP3 or M4A format
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Audio {
    /// Duration of the audio, in seconds; as defined by the sender
    pub duration: i32,
    /// Title of the audio; as defined by the sender
    pub title: String,
    /// Performer of the audio; as defined by the sender
    pub performer: String,
    /// Original name of the file; as defined by the sender
    pub file_name: String,
    /// The MIME type of the file; as defined by the sender
    pub mime_type: String,
    /// The minithumbnail of the album cover; may be null
    pub album_cover_minithumbnail: Option<crate::types::Minithumbnail>,
    /// The thumbnail of the album cover in JPEG format; as defined by the sender. The full size thumbnail is expected to be extracted from the downloaded audio file; may be null
    pub album_cover_thumbnail: Option<crate::types::Thumbnail>,
    /// Album cover variants to use if the downloaded audio file contains no album cover. Provided thumbnail dimensions are approximate
    pub external_album_covers: Vec<crate::types::Thumbnail>,
    /// File containing the audio
    pub audio: crate::types::File,
}

/// Contains a list of audio files
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct Audios {
    /// Approximate total number of audio files found
    pub total_count: i32,
    /// List of audio files
    pub audios: Vec<crate::types::Audio>,
}

/// Describes a document of any type
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Document {
    /// Original name of the file; as defined by the sender
    pub file_name: String,
    /// MIME type of the file; as defined by the sender
    pub mime_type: String,
    /// Document minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// Document thumbnail in JPEG or PNG format (PNG will be used only for background patterns); as defined by the sender; may be null
    pub thumbnail: Option<crate::types::Thumbnail>,
    /// File containing the document
    pub document: crate::types::File,
}

/// Describes a photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct Photo {
    /// True, if stickers were added to the photo. The list of corresponding sticker sets can be received using getAttachedStickerSets
    pub has_stickers: bool,
    /// Photo minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// Available variants of the photo, in different sizes
    pub sizes: Vec<crate::types::PhotoSize>,
}

/// Describes a video file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Video {
    /// Duration of the video, in seconds; as defined by the sender
    pub duration: i32,
    /// Video width; as defined by the sender
    pub width: i32,
    /// Video height; as defined by the sender
    pub height: i32,
    /// Original name of the file; as defined by the sender
    pub file_name: String,
    /// MIME type of the file; as defined by the sender
    pub mime_type: String,
    /// True, if stickers were added to the video. The list of corresponding sticker sets can be received using getAttachedStickerSets
    pub has_stickers: bool,
    /// True, if the video is expected to be streamed
    pub supports_streaming: bool,
    /// Video minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// Video thumbnail in JPEG or MPEG4 format; as defined by the sender; may be null
    pub thumbnail: Option<crate::types::Thumbnail>,
    /// File containing the video
    pub video: crate::types::File,
}

/// Describes a video note. The video must be equal in width and height, cropped to a circle, and stored in MPEG4 format
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct VideoNote {
    /// Duration of the video, in seconds; as defined by the sender
    pub duration: i32,
    /// A waveform representation of the video note's audio in 5-bit format; may be empty if unknown
    pub waveform: String,
    /// Video width and height; as defined by the sender
    pub length: i32,
    /// Video minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// Video thumbnail in JPEG format; as defined by the sender; may be null
    pub thumbnail: Option<crate::types::Thumbnail>,
    /// Result of speech recognition in the video note; may be null
    pub speech_recognition_result: Option<crate::enums::SpeechRecognitionResult>,
    /// File containing the video
    pub video: crate::types::File,
}

/// Describes an alternative re-encoded quality of a video file
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct AlternativeVideo {
    /// Unique identifier of the alternative video, which is used in the HLS file
    #[serde_as(as = "DisplayFromStr")]
    pub id: i64,
    /// Video width
    pub width: i32,
    /// Video height
    pub height: i32,
    /// Codec used for video file encoding, for example, "h264", "h265", "av1", or "av01"
    pub codec: String,
    /// HLS file describing the video
    pub hls_file: crate::types::File,
    /// File containing the video
    pub video: crate::types::File,
}

/// Describes a user profile photo
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfilePhoto {
    /// Photo identifier; 0 for an empty photo. Can be used to find a photo in a list of user profile photos
    #[serde_as(as = "DisplayFromStr")]
    pub id: i64,
    /// A small (160x160) user profile photo. The file can be downloaded only before the photo is changed
    pub small: crate::types::File,
    /// A big (640x640) user profile photo. The file can be downloaded only before the photo is changed
    pub big: crate::types::File,
    /// User profile photo minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// True, if the photo has animated variant
    pub has_animation: bool,
    /// True, if the photo is visible only for the current user
    pub is_personal: bool,
}

/// Contains basic information about the photo of a chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatPhotoInfo {
    /// A small (160x160) chat photo variant in JPEG format. The file can be downloaded only before the photo is changed
    pub small: crate::types::File,
    /// A big (640x640) chat photo variant in JPEG format. The file can be downloaded only before the photo is changed
    pub big: crate::types::File,
    /// Chat photo minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// True, if the photo has animated variant
    pub has_animation: bool,
    /// True, if the photo is visible only for the current user
    pub is_personal: bool,
}

/// A tab with stories posted by the user or the channel chat and saved to profile
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabPosts {
}

/// A tab with gifts received by the user or the channel chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabGifts {
}

/// A tab with photos and videos posted by the channel
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabMedia {
}

/// A tab with documents posted by the channel
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabFiles {
}

/// A tab with messages posted by the channel and containing links
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabLinks {
}

/// A tab with audio messages posted by the channel
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabMusic {
}

/// A tab with voice notes posted by the channel
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabVoice {
}

/// A tab with animations posted by the channel
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileTabGifs {
}

/// Describes a chat or user profile photo
#[serde_as]
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ChatPhoto {
    /// Unique photo identifier
    #[serde_as(as = "DisplayFromStr")]
    pub id: i64,
    /// Point in time (Unix timestamp) when the photo has been added
    pub added_date: i32,
    /// Photo minithumbnail; may be null
    pub minithumbnail: Option<crate::types::Minithumbnail>,
    /// Available variants of the photo in JPEG format, in different size
    pub sizes: Vec<crate::types::PhotoSize>,
    /// A big (up to 1280x1280) animated variant of the photo in MPEG4 format; may be null
    pub animation: Option<crate::types::AnimatedChatPhoto>,
    /// A small (160x160) animated variant of the photo in MPEG4 format; may be null even if the big animation is available
    pub small_animation: Option<crate::types::AnimatedChatPhoto>,
    /// Sticker-based version of the chat photo; may be null
    pub sticker: Option<crate::types::ChatPhotoSticker>,
}

/// Contains a list of chat or user profile photos
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatPhotos {
    /// Total number of photos
    pub total_count: i32,
    /// List of photos
    pub photos: Vec<crate::types::ChatPhoto>,
}

/// A previously used profile photo of the current user
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputChatPhotoPrevious {
    /// Identifier of the current user's profile photo to reuse
    #[serde_as(as = "DisplayFromStr")]
    pub chat_photo_id: i64,
}

/// A static photo in JPEG format
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputChatPhotoStatic {
    /// Photo to be set as profile photo. Only inputFileLocal and inputFileGenerated are allowed
    pub photo: crate::enums::InputFile,
}

/// An animation in MPEG4 format; must be square, at most 10 seconds long, have width between 160 and 1280 and be at most 2MB in size
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputChatPhotoAnimation {
    /// Animation to be set as profile photo. Only inputFileLocal and inputFileGenerated are allowed
    pub animation: crate::enums::InputFile,
    /// Timestamp of the frame, which will be used as static chat photo
    pub main_frame_timestamp: f64,
}

/// Contains information about supported accent colors for user profile photo background in RGB format
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileAccentColors {
    /// The list of 1-2 colors in RGB format, describing the colors, as expected to be shown in the color palette settings
    pub palette_colors: Vec<i32>,
    /// The list of 1-2 colors in RGB format, describing the colors, as expected to be used for the profile photo background
    pub background_colors: Vec<i32>,
    /// The list of 2 colors in RGB format, describing the colors of the gradient to be used for the unread active story indicator around profile photo
    pub story_colors: Vec<i32>,
}

/// Contains information about supported accent color for user profile photo background
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ProfileAccentColor {
    /// Profile accent color identifier
    pub id: i32,
    /// Accent colors expected to be used in light themes
    pub light_theme_colors: crate::types::ProfileAccentColors,
    /// Accent colors expected to be used in dark themes
    pub dark_theme_colors: crate::types::ProfileAccentColors,
    /// The minimum chat boost level required to use the color in a supergroup chat
    pub min_supergroup_chat_boost_level: i32,
    /// The minimum chat boost level required to use the color in a channel chat
    pub min_channel_chat_boost_level: i32,
}

/// Describes an advertisement to be shown while a video from a message is watched
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct VideoMessageAdvertisement {
    /// Unique identifier of this result
    pub unique_id: i64,
    /// Text of the advertisement
    pub text: String,
    /// The minimum amount of time the advertisement must be displayed before it can be hidden by the user, in seconds
    pub min_display_duration: i32,
    /// The maximum amount of time the advertisement must be displayed before it must be automatically hidden, in seconds
    pub max_display_duration: i32,
    /// True, if the advertisement can be reported to Telegram moderators through reportVideoMessageAdvertisement
    pub can_be_reported: bool,
    /// Information about the sponsor of the advertisement
    pub sponsor: crate::types::AdvertisementSponsor,
    /// Title of the sponsored message
    pub title: String,
    /// If non-empty, additional information about the sponsored message to be shown along with the message
    pub additional_info: String,
}

/// Contains a list of advertisements to be shown while a video from a message is watched
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct VideoMessageAdvertisements {
    /// List of advertisements
    pub advertisements: Vec<crate::types::VideoMessageAdvertisement>,
    /// Delay before the first advertisement is shown, in seconds
    pub start_delay: i32,
    /// Delay between consecutive advertisements, in seconds
    pub between_delay: i32,
}

/// Describes a file added to file download list
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct FileDownload {
    /// File identifier
    pub file_id: i32,
    /// The message with the file
    pub message: crate::types::Message,
    /// Point in time (Unix timestamp) when the file was added to the download list
    pub add_date: i32,
    /// Point in time (Unix timestamp) when the file downloading was completed; 0 if the file downloading isn't completed
    pub complete_date: i32,
    /// True, if downloading of the file is paused
    pub is_paused: bool,
}

/// Contains number of being downloaded and recently downloaded files found
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct DownloadedFileCounts {
    /// Number of active file downloads found, including paused
    pub active_count: i32,
    /// Number of paused file downloads found
    pub paused_count: i32,
    /// Number of completed file downloads found
    pub completed_count: i32,
}

/// Contains a list of downloaded files, found by a search
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FoundFileDownloads {
    /// Total number of suitable files, ignoring offset
    pub total_counts: crate::types::DownloadedFileCounts,
    /// The list of files
    pub files: Vec<crate::types::FileDownload>,
    /// The offset for the next request. If empty, then there are no more results
    pub next_offset: String,
}

/// A video note message draft
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct DraftMessageContentVideoNote {
    /// Path to the file with the video note
    pub file_path: String,
    /// Duration of the video, in seconds; 0-60
    pub duration: i32,
    /// Video width and height; must be positive and not greater than 640
    pub length: i32,
    /// Video note self-destruct type; may be null if none; pass null if none; private chats only
    pub self_destruct_type: Option<crate::enums::MessageSelfDestructType>,
}

/// Describes a video chat, i.e. a group call bound to a chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct VideoChat {
    /// Group call identifier of an active video chat; 0 if none. Full information about the video chat can be received through the method getGroupCall
    pub group_call_id: i32,
    /// True, if the video chat has participants
    pub has_participants: bool,
    /// Default group call participant identifier to join the video chat; may be null
    pub default_participant_id: Option<crate::enums::MessageSender>,
}

/// An animation
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PageBlockAnimation {
    /// Animation file; may be null
    pub animation: Option<crate::types::Animation>,
    /// Animation caption; may be null if none
    pub caption: Option<crate::types::PageBlockCaption>,
    /// True, if the animation must be played automatically
    pub need_autoplay: bool,
    /// True, if the animation preview must be covered by a spoiler animation
    pub has_spoiler: bool,
}

/// An audio file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PageBlockAudio {
    /// Audio file
    pub audio: crate::types::Audio,
    /// Audio file caption; may be null if none
    pub caption: Option<crate::types::PageBlockCaption>,
}

/// A general file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PageBlockDocument {
    /// The file
    pub document: crate::types::Document,
    /// File caption; may be null if none
    pub caption: Option<crate::types::PageBlockCaption>,
}

/// A photo
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PageBlockPhoto {
    /// Photo file; may be null
    pub photo: Option<crate::types::Photo>,
    /// Photo caption; may be null if none
    pub caption: Option<crate::types::PageBlockCaption>,
    /// URL that needs to be opened when the photo is clicked; instant view only
    pub url: String,
    /// True, if the photo preview must be covered by a spoiler animation
    pub has_spoiler: bool,
}

/// A video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PageBlockVideo {
    /// Video file; may be null
    pub video: Option<crate::types::Video>,
    /// Video caption; may be null if none
    pub caption: Option<crate::types::PageBlockCaption>,
    /// True, if the video must be played automatically
    pub need_autoplay: bool,
    /// True, if the video must be looped
    pub is_looped: bool,
    /// True, if the video preview must be covered by a spoiler animation
    pub has_spoiler: bool,
}

/// The media is a photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewAlbumMediaPhoto {
    /// Photo description
    pub photo: crate::types::Photo,
}

/// The media is a video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewAlbumMediaVideo {
    /// Video description
    pub video: crate::types::Video,
}

/// The link is a link to an animation
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeAnimation {
    /// The animation
    pub animation: crate::types::Animation,
}

/// The link is a link to an audio
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeAudio {
    /// The audio description
    pub audio: crate::types::Audio,
}

/// The link is a link to a general file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeDocument {
    /// The document description
    pub document: crate::types::Document,
}

/// The link is a link to an animation player
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeEmbeddedAnimationPlayer {
    /// URL of the external animation player
    pub url: String,
    /// The cached animation; may be null if unknown
    pub animation: Option<crate::types::Animation>,
    /// Thumbnail of the animation; may be null if unknown
    pub thumbnail: Option<crate::types::Photo>,
    /// Duration of the animation, in seconds
    pub duration: i32,
    /// Expected width of the embedded player
    pub width: i32,
    /// Expected height of the embedded player
    pub height: i32,
}

/// The link is a link to an audio player
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeEmbeddedAudioPlayer {
    /// URL of the external audio player
    pub url: String,
    /// The cached audio; may be null if unknown
    pub audio: Option<crate::types::Audio>,
    /// Thumbnail of the audio; may be null if unknown
    pub thumbnail: Option<crate::types::Photo>,
    /// Duration of the audio, in seconds
    pub duration: i32,
    /// Expected width of the embedded player
    pub width: i32,
    /// Expected height of the embedded player
    pub height: i32,
}

/// The link is a link to a video player
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeEmbeddedVideoPlayer {
    /// URL of the external video player
    pub url: String,
    /// The cached video; may be null if unknown
    pub video: Option<crate::types::Video>,
    /// Thumbnail of the video; may be null if unknown
    pub thumbnail: Option<crate::types::Photo>,
    /// Duration of the video, in seconds
    pub duration: i32,
    /// Expected width of the embedded player
    pub width: i32,
    /// Expected height of the embedded player
    pub height: i32,
}

/// The link is a link to an audio file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeExternalAudio {
    /// URL of the audio file
    pub url: String,
    /// MIME type of the audio file
    pub mime_type: String,
    /// Duration of the audio, in seconds; 0 if unknown
    pub duration: i32,
}

/// The link is a link to a video file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeExternalVideo {
    /// URL of the video file
    pub url: String,
    /// MIME type of the video file
    pub mime_type: String,
    /// Expected width of the video preview; 0 if unknown
    pub width: i32,
    /// Expected height of the video preview; 0 if unknown
    pub height: i32,
    /// Duration of the video, in seconds; 0 if unknown
    pub duration: i32,
}

/// The link is a link to a photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypePhoto {
    /// The photo
    pub photo: crate::types::Photo,
}

/// The link is a link to a video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeVideo {
    /// The video description
    pub video: crate::types::Video,
    /// Cover of the video; may be null if none
    pub cover: Option<crate::types::Photo>,
    /// Timestamp from which the video playing must start, in seconds
    pub start_timestamp: i32,
}

/// The link is a link to a video chat
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeVideoChat {
    /// Photo of the chat with the video chat; may be null if none
    pub photo: Option<crate::types::ChatPhoto>,
    /// True, if the video chat is expected to be a live stream in a channel or a broadcast group
    pub is_live_stream: bool,
    /// True, if the user can use the link to join the video chat without being muted by administrators
    pub joins_as_speaker: bool,
}

/// The link is a link to a video note message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkPreviewTypeVideoNote {
    /// The video note
    pub video_note: crate::types::VideoNote,
}

/// The media is a photo
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PaidMediaPhoto {
    /// The photo
    pub photo: crate::types::Photo,
    /// The video representing the live photo; may be null if the photo is static
    pub video: Option<crate::types::Video>,
}

/// The media is a video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PaidMediaVideo {
    /// The video
    pub video: crate::types::Video,
    /// Cover of the video; may be null if none
    pub cover: Option<crate::types::Photo>,
    /// Timestamp from which the video playing must start, in seconds
    pub start_timestamp: i32,
}

/// File with the date it was uploaded
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct DatedFile {
    /// The file
    pub file: crate::types::File,
    /// Point in time (Unix timestamp) when the file was uploaded
    pub date: i32,
}

/// An identity document
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct IdentityDocument {
    /// Document number; 1-24 characters
    pub number: String,
    /// Document expiration date; may be null if not applicable
    pub expiration_date: Option<crate::types::Date>,
    /// Front side of the document
    pub front_side: crate::types::DatedFile,
    /// Reverse side of the document; only for driver license and identity card; may be null
    pub reverse_side: Option<crate::types::DatedFile>,
    /// Selfie with the document; may be null
    pub selfie: Option<crate::types::DatedFile>,
    /// List of files containing a certified English translation of the document
    pub translation: Vec<crate::types::DatedFile>,
}

/// An identity document to be saved to Telegram Passport
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputIdentityDocument {
    /// Document number; 1-24 characters
    pub number: String,
    /// Document expiration date; pass null if not applicable
    pub expiration_date: Option<crate::types::Date>,
    /// Front side of the document
    pub front_side: crate::enums::InputFile,
    /// Reverse side of the document; only for driver license and identity card; pass null otherwise
    pub reverse_side: Option<crate::enums::InputFile>,
    /// Selfie with the document; pass null if unavailable
    pub selfie: Option<crate::enums::InputFile>,
    /// List of files containing a certified English translation of the document
    pub translation: Vec<crate::enums::InputFile>,
}

/// A personal document, containing some information about a user
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PersonalDocument {
    /// List of files containing the pages of the document
    pub files: Vec<crate::types::DatedFile>,
    /// List of files containing a certified English translation of the document
    pub translation: Vec<crate::types::DatedFile>,
}

/// A personal document to be saved to Telegram Passport
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputPersonalDocument {
    /// List of files containing the pages of the document
    pub files: Vec<crate::enums::InputFile>,
    /// List of files containing a certified English translation of the document
    pub translation: Vec<crate::enums::InputFile>,
}

/// An animation message (GIF-style).
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageAnimation {
    /// The animation description
    pub animation: crate::types::Animation,
    /// Animation caption
    pub caption: crate::types::FormattedText,
    /// True, if the caption must be shown above the animation; otherwise, the caption must be shown below the animation
    pub show_caption_above_media: bool,
    /// True, if the animation preview must be covered by a spoiler animation
    pub has_spoiler: bool,
    /// True, if the animation thumbnail must be blurred and the animation must be shown only while tapped
    pub is_secret: bool,
}

/// An audio message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageAudio {
    /// The audio description
    pub audio: crate::types::Audio,
    /// Audio caption
    pub caption: crate::types::FormattedText,
}

/// A document message (general file)
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageDocument {
    /// The document description
    pub document: crate::types::Document,
    /// Document caption
    pub caption: crate::types::FormattedText,
}

/// A photo message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessagePhoto {
    /// The photo
    pub photo: crate::types::Photo,
    /// The video representing the live photo; may be null if the photo is static
    pub video: Option<crate::types::Video>,
    /// Photo caption
    pub caption: crate::types::FormattedText,
    /// True, if the caption must be shown above the photo; otherwise, the caption must be shown below the photo
    pub show_caption_above_media: bool,
    /// True, if the photo preview must be covered by a spoiler animation
    pub has_spoiler: bool,
    /// True, if the photo must be blurred and must be shown only while tapped
    pub is_secret: bool,
}

/// A video message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageVideo {
    /// The video description
    pub video: crate::types::Video,
    /// Alternative qualities of the video
    pub alternative_videos: Vec<crate::types::AlternativeVideo>,
    /// Available storyboards for the video
    pub storyboards: Vec<crate::types::VideoStoryboard>,
    /// Cover of the video; may be null if none
    pub cover: Option<crate::types::Photo>,
    /// Timestamp from which the video playing must start, in seconds
    pub start_timestamp: i32,
    /// Video caption
    pub caption: crate::types::FormattedText,
    /// True, if the caption must be shown above the video; otherwise, the caption must be shown below the video
    pub show_caption_above_media: bool,
    /// True, if the video preview must be covered by a spoiler animation
    pub has_spoiler: bool,
    /// True, if the video thumbnail must be blurred and the video must be shown only while tapped
    pub is_secret: bool,
}

/// A video note message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageVideoNote {
    /// The video note description
    pub video_note: crate::types::VideoNote,
    /// True, if at least one of the recipients has viewed the video note
    pub is_viewed: bool,
    /// True, if the video note thumbnail must be blurred and the video note must be shown only while tapped
    pub is_secret: bool,
}

/// A self-destructed photo message
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageExpiredPhoto {
}

/// A self-destructed video message
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageExpiredVideo {
}

/// A self-destructed video note message
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageExpiredVideoNote {
}

/// A new video chat was scheduled
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageVideoChatScheduled {
    /// Identifier of the video chat. The video chat can be received through the method getGroupCall
    pub group_call_id: i32,
    /// Point in time (Unix timestamp) when the group call is expected to be started by an administrator
    pub start_date: i32,
}

/// A newly created video chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageVideoChatStarted {
    /// Identifier of the video chat. The video chat can be received through the method getGroupCall
    pub group_call_id: i32,
}

/// A message with information about an ended video chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageVideoChatEnded {
    /// Call duration, in seconds
    pub duration: i32,
}

/// A message with information about an invitation to a video chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageInviteVideoChatParticipants {
    /// Identifier of the video chat. The video chat can be received through the method getGroupCall
    pub group_call_id: i32,
    /// Invited user identifiers
    pub user_ids: Vec<i64>,
}

/// An updated chat photo
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageChatChangePhoto {
    /// New chat photo
    pub photo: crate::types::ChatPhoto,
}

/// A deleted chat photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageChatDeletePhoto {
}

/// A profile photo was suggested to a user in a private chat
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct MessageSuggestProfilePhoto {
    /// The suggested chat photo. Use the method setProfilePhoto with inputChatPhotoPrevious to apply the photo
    pub photo: crate::types::ChatPhoto,
}

/// A thumbnail to be sent along with a file; must be in JPEG or WEBP format for stickers, and less than 200 KB in size
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputThumbnail {
    /// Thumbnail file to send. Sending thumbnails by file_id is currently not supported
    pub thumbnail: crate::enums::InputFile,
    /// Thumbnail width, usually shouldn't exceed 320. Use 0 if unknown
    pub width: i32,
    /// Thumbnail height, usually shouldn't exceed 320. Use 0 if unknown
    pub height: i32,
}

/// An animation to be sent
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputAnimation {
    /// Animation file to be sent
    pub animation: crate::enums::InputFile,
    /// Animation thumbnail; pass null to skip thumbnail uploading
    pub thumbnail: Option<crate::types::InputThumbnail>,
    /// File identifiers of the stickers added to the animation, if applicable
    pub added_sticker_file_ids: Vec<i32>,
    /// Duration of the animation, in seconds; may be replaced by the server
    pub duration: i32,
    /// Width of the animation; may be replaced by the server
    pub width: i32,
    /// Height of the animation; may be replaced by the server
    pub height: i32,
}

/// An audio to be sent
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputAudio {
    /// Audio file to be sent
    pub audio: crate::enums::InputFile,
    /// Thumbnail of the cover for the album; pass null to skip thumbnail uploading
    pub album_cover_thumbnail: Option<crate::types::InputThumbnail>,
    /// Duration of the audio, in seconds; may be replaced by the server
    pub duration: i32,
    /// Title of the audio; 0-64 characters; may be replaced by the server
    pub title: String,
    /// Performer of the audio; 0-64 characters, may be replaced by the server
    pub performer: String,
}

/// A document (general file) to be sent
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputDocument {
    /// File to be sent
    pub document: crate::enums::InputFile,
    /// Document thumbnail; pass null to skip thumbnail uploading
    pub thumbnail: Option<crate::types::InputThumbnail>,
    /// Pass true to disable automatic file type detection and send the document as a file. Always true for files sent to secret chats
    pub disable_content_type_detection: bool,
}

/// A photo to be sent
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputPhoto {
    /// Photo to be sent. The photo must be at most 10 MB in size. The photo's width and height must not exceed 10000 in total. Width and height ratio must be at most 20
    pub photo: crate::enums::InputFile,
    /// Photo thumbnail; pass null to skip thumbnail uploading. The thumbnail is sent to the other party only in secret chats
    pub thumbnail: Option<crate::types::InputThumbnail>,
    /// Video of the live photo; not supported in secret chats; pass null if the photo isn't a live photo
    pub video: Option<crate::enums::InputFile>,
    /// File identifiers of the stickers added to the photo, if applicable
    pub added_sticker_file_ids: Vec<i32>,
    /// Photo width; may be replaced by the server
    pub width: i32,
    /// Photo height; may be replaced by the server
    pub height: i32,
}

/// A video to be sent
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputVideo {
    /// Video file to be sent. The video is expected to be re-encoded to MPEG4 format with H.264 codec by the sender
    pub video: crate::enums::InputFile,
    /// Video thumbnail; pass null to skip thumbnail uploading
    pub thumbnail: Option<crate::types::InputThumbnail>,
    /// Cover of the video; pass null to skip cover uploading; not supported in secret chats and for self-destructing messages
    pub cover: Option<crate::enums::InputFile>,
    /// Timestamp from which the video playing must start, in seconds
    pub start_timestamp: i32,
    /// File identifiers of the stickers added to the video, if applicable
    pub added_sticker_file_ids: Vec<i32>,
    /// Duration of the video, in seconds
    pub duration: i32,
    /// Video width
    pub width: i32,
    /// Video height
    pub height: i32,
    /// True, if the video is expected to be streamed
    pub supports_streaming: bool,
}

/// A video note to be sent
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputVideoNote {
    /// Video note file to be sent. The video is expected to be encoded to MPEG4 format with H.264 codec and have no data outside of the visible circle
    pub video_note: crate::enums::InputFile,
    /// Video thumbnail; may be null if empty; pass null to skip thumbnail uploading
    pub thumbnail: Option<crate::types::InputThumbnail>,
    /// Duration of the video, in seconds; 0-60
    pub duration: i32,
    /// Video width and height; must be positive and not greater than 640
    pub length: i32,
}

/// The media is a photo. The photo must be at most 10 MB in size. The photo's width and height must not exceed 10000 in total. Width and height ratio must be at most 20
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputPaidMediaTypePhoto {
    /// Video of the live photo; pass null if the photo isn't a live photo
    pub video: Option<crate::enums::InputFile>,
}

/// The media is a video
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputPaidMediaTypeVideo {
    /// Cover of the video; pass null to skip cover uploading
    pub cover: Option<crate::enums::InputFile>,
    /// Timestamp from which the video playing must start, in seconds
    pub start_timestamp: i32,
    /// Duration of the video, in seconds
    pub duration: i32,
    /// True, if the video is expected to be streamed
    pub supports_streaming: bool,
}

/// The message will be sent when the video in the message is converted and optimized; can be used only by the server
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageSchedulingStateSendWhenVideoProcessed {
    /// Approximate point in time (Unix timestamp) when the message is expected to be sent
    pub send_date: i32,
}

/// An animation
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputPageBlockAnimation {
    /// The animation to be sent
    pub animation: crate::types::InputAnimation,
    /// Animation caption; pass null if none
    pub caption: Option<crate::types::PageBlockCaption>,
    /// True, if the animation preview must be covered by a spoiler animation
    pub has_spoiler: bool,
}

/// An audio file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputPageBlockAudio {
    /// The audio to be sent
    pub audio: crate::types::InputAudio,
    /// Audio file caption; pass null if none
    pub caption: Option<crate::types::PageBlockCaption>,
}

/// A general file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputPageBlockDocument {
    /// The file to be sent
    pub document: crate::types::InputDocument,
    /// File caption; pass null if none
    pub caption: Option<crate::types::PageBlockCaption>,
}

/// A photo
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputPageBlockPhoto {
    /// The photo to be sent
    pub photo: crate::types::InputPhoto,
    /// Photo caption; pass null if none
    pub caption: Option<crate::types::PageBlockCaption>,
    /// True, if the photo preview must be covered by a spoiler animation
    pub has_spoiler: bool,
}

/// A video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputPageBlockVideo {
    /// The video to be sent
    pub video: crate::types::InputVideo,
    /// Video caption; pass null if none
    pub caption: Option<crate::types::PageBlockCaption>,
    /// True, if the video preview must be covered by a spoiler animation
    pub has_spoiler: bool,
}

/// An animation message (GIF-style).
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputMessageAnimation {
    /// The animation to be sent
    pub animation: crate::types::InputAnimation,
    /// Animation caption; pass null to use an empty caption; 0-getOption("message_caption_length_max") characters
    pub caption: Option<crate::types::FormattedText>,
    /// True, if the caption must be shown above the animation; otherwise, the caption must be shown below the animation; not supported in secret chats
    pub show_caption_above_media: bool,
    /// True, if the animation preview must be covered by a spoiler animation; not supported in secret chats
    pub has_spoiler: bool,
}

/// An audio message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputMessageAudio {
    /// Audio to be sent
    pub audio: crate::types::InputAudio,
    /// Audio caption; pass null to use an empty caption; 0-getOption("message_caption_length_max") characters
    pub caption: Option<crate::types::FormattedText>,
}

/// A document message (general file)
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputMessageDocument {
    /// Document to be sent
    pub document: crate::types::InputDocument,
    /// Document caption; pass null to use an empty caption; 0-getOption("message_caption_length_max") characters
    pub caption: Option<crate::types::FormattedText>,
}

/// A photo message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputMessagePhoto {
    /// Photo to be sent
    pub photo: crate::types::InputPhoto,
    /// Photo caption; pass null to use an empty caption; 0-getOption("message_caption_length_max") characters
    pub caption: Option<crate::types::FormattedText>,
    /// True, if the caption must be shown above the photo; otherwise, the caption must be shown below the photo; not supported in secret chats
    pub show_caption_above_media: bool,
    /// Photo self-destruct type; pass null if none; private chats only
    pub self_destruct_type: Option<crate::enums::MessageSelfDestructType>,
    /// True, if the photo preview must be covered by a spoiler animation; not supported in secret chats
    pub has_spoiler: bool,
}

/// A video message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputMessageVideo {
    /// Video to be sent
    pub video: crate::types::InputVideo,
    /// Video caption; pass null to use an empty caption; 0-getOption("message_caption_length_max") characters
    pub caption: Option<crate::types::FormattedText>,
    /// True, if the caption must be shown above the video; otherwise, the caption must be shown below the video; not supported in secret chats
    pub show_caption_above_media: bool,
    /// Video self-destruct type; pass null if none; private chats only
    pub self_destruct_type: Option<crate::enums::MessageSelfDestructType>,
    /// True, if the video preview must be covered by a spoiler animation; not supported in secret chats
    pub has_spoiler: bool,
}

/// A video note message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputMessageVideoNote {
    /// Video note to be sent
    pub video_note: crate::types::InputVideoNote,
    /// Video note self-destruct type; may be null if none; pass null if none; private chats only
    pub self_destruct_type: Option<crate::enums::MessageSelfDestructType>,
}

/// Returns only animation messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterAnimation {
}

/// Returns only audio messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterAudio {
}

/// Returns only document messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterDocument {
}

/// Returns only photo messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterPhoto {
}

/// Returns only video messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterVideo {
}

/// Returns only photo and video messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterPhotoAndVideo {
}

/// Returns only messages containing chat photos
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterChatPhoto {
}

/// Returns only video note messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterVideoNote {
}

/// Returns only voice and video note messages
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SearchMessagesFilterVoiceAndVideoNote {
}

/// The user is recording a video
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionRecordingVideo {
}

/// The user is uploading a video
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionUploadingVideo {
    /// Upload progress, as a percentage
    pub progress: i32,
}

/// The user is uploading a photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionUploadingPhoto {
    /// Upload progress, as a percentage
    pub progress: i32,
}

/// The user is uploading a document
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionUploadingDocument {
    /// Upload progress, as a percentage
    pub progress: i32,
}

/// The user is recording a video note
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionRecordingVideoNote {
}

/// The user is uploading a video note
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionUploadingVideoNote {
    /// Upload progress, as a percentage
    pub progress: i32,
}

/// The user is watching animations sent by the other party by clicking on an animated emoji
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatActionWatchingAnimations {
    /// The animated emoji
    pub emoji: String,
}

/// Represents a list of animations
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct Animations {
    /// List of animations
    pub animations: Vec<crate::types::Animation>,
}

/// Represents a link to an animated GIF or an animated (i.e., without sound) H.264/MPEG-4 AVC video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputInlineQueryResultAnimation {
    /// Unique identifier of the query result
    pub id: String,
    /// Title of the query result
    pub title: String,
    /// URL of the result thumbnail (JPEG, GIF, or MPEG4), if it exists
    pub thumbnail_url: String,
    /// MIME type of the video thumbnail. If non-empty, must be one of "image/jpeg", "image/gif" and "video/mp4"
    pub thumbnail_mime_type: String,
    /// The URL of the video file (file size must not exceed 1MB)
    pub video_url: String,
    /// MIME type of the video file. Must be one of "image/gif" and "video/mp4"
    pub video_mime_type: String,
    /// Duration of the video, in seconds
    pub video_duration: i32,
    /// Width of the video
    pub video_width: i32,
    /// Height of the video
    pub video_height: i32,
    /// The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
    pub reply_markup: Option<crate::enums::ReplyMarkup>,
    /// The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageRichMessage, inputMessageAnimation, inputMessageInvoice, inputMessageLiveLocation, inputMessageLocation, inputMessageVenue or inputMessageContact
    pub input_message_content: crate::enums::InputMessageContent,
}

/// Represents a link to an MP3 audio file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputInlineQueryResultAudio {
    /// Unique identifier of the query result
    pub id: String,
    /// Title of the audio file
    pub title: String,
    /// Performer of the audio file
    pub performer: String,
    /// The URL of the audio file
    pub audio_url: String,
    /// Audio file duration, in seconds
    pub audio_duration: i32,
    /// The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
    pub reply_markup: Option<crate::enums::ReplyMarkup>,
    /// The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageRichMessage, inputMessageAudio, inputMessageInvoice, inputMessageLiveLocation, inputMessageLocation, inputMessageVenue or inputMessageContact
    pub input_message_content: crate::enums::InputMessageContent,
}

/// Represents a link to a file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputInlineQueryResultDocument {
    /// Unique identifier of the query result
    pub id: String,
    /// Title of the resulting file
    pub title: String,
    /// Short description of the result, if known
    pub description: String,
    /// URL of the file
    pub document_url: String,
    /// MIME type of the file content; only "application/pdf" and "application/zip" are currently allowed
    pub mime_type: String,
    /// The URL of the file thumbnail, if it exists
    pub thumbnail_url: String,
    /// Width of the thumbnail
    pub thumbnail_width: i32,
    /// Height of the thumbnail
    pub thumbnail_height: i32,
    /// The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
    pub reply_markup: Option<crate::enums::ReplyMarkup>,
    /// The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageRichMessage, inputMessageDocument, inputMessageInvoice, inputMessageLiveLocation, inputMessageLocation, inputMessageVenue or inputMessageContact
    pub input_message_content: crate::enums::InputMessageContent,
}

/// Represents link to a JPEG image
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputInlineQueryResultPhoto {
    /// Unique identifier of the query result
    pub id: String,
    /// Title of the result, if known
    pub title: String,
    /// A short description of the result, if known
    pub description: String,
    /// URL of the photo thumbnail, if it exists
    pub thumbnail_url: String,
    /// The URL of the JPEG photo (photo size must not exceed 5MB)
    pub photo_url: String,
    /// Width of the photo
    pub photo_width: i32,
    /// Height of the photo
    pub photo_height: i32,
    /// The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
    pub reply_markup: Option<crate::enums::ReplyMarkup>,
    /// The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageRichMessage, inputMessagePhoto, inputMessageInvoice, inputMessageLiveLocation, inputMessageLocation, inputMessageVenue or inputMessageContact
    pub input_message_content: crate::enums::InputMessageContent,
}

/// Represents a link to a page containing an embedded video player or a video file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InputInlineQueryResultVideo {
    /// Unique identifier of the query result
    pub id: String,
    /// Title of the result
    pub title: String,
    /// A short description of the result, if known
    pub description: String,
    /// The URL of the video thumbnail (JPEG), if it exists
    pub thumbnail_url: String,
    /// URL of the embedded video player or video file
    pub video_url: String,
    /// MIME type of the content of the video URL, only "text/html" or "video/mp4" are currently supported
    pub mime_type: String,
    /// Width of the video
    pub video_width: i32,
    /// Height of the video
    pub video_height: i32,
    /// Video duration, in seconds
    pub video_duration: i32,
    /// The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
    pub reply_markup: Option<crate::enums::ReplyMarkup>,
    /// The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageRichMessage, inputMessageVideo, inputMessageInvoice, inputMessageLiveLocation, inputMessageLocation, inputMessageVenue or inputMessageContact
    pub input_message_content: crate::enums::InputMessageContent,
}

/// Represents an animation file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InlineQueryResultAnimation {
    /// Unique identifier of the query result
    pub id: String,
    /// Animation file
    pub animation: crate::types::Animation,
    /// Animation title
    pub title: String,
}

/// Represents an audio file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InlineQueryResultAudio {
    /// Unique identifier of the query result
    pub id: String,
    /// Audio file
    pub audio: crate::types::Audio,
}

/// Represents a document
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InlineQueryResultDocument {
    /// Unique identifier of the query result
    pub id: String,
    /// Document
    pub document: crate::types::Document,
    /// Document title
    pub title: String,
    /// Document description
    pub description: String,
}

/// Represents a photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InlineQueryResultPhoto {
    /// Unique identifier of the query result
    pub id: String,
    /// Photo
    pub photo: crate::types::Photo,
    /// Title of the result, if known
    pub title: String,
    /// A short description of the result, if known
    pub description: String,
}

/// Represents a video
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct InlineQueryResultVideo {
    /// Unique identifier of the query result
    pub id: String,
    /// Video
    pub video: crate::types::Video,
    /// Title of the video
    pub title: String,
    /// Description of the video
    pub description: String,
}

/// The chat photo was changed
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ChatEventPhotoChanged {
    /// Previous chat photo value; may be null
    pub old_photo: Option<crate::types::ChatPhoto>,
    /// New chat photo value; may be null
    pub new_photo: Option<crate::types::ChatPhoto>,
}

/// The chat's profile accent color or profile background custom emoji were changed
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatEventProfileAccentColorChanged {
    /// Previous identifier of chat's profile accent color; -1 if none
    pub old_profile_accent_color_id: i32,
    /// Previous identifier of the custom emoji; 0 if none
    #[serde_as(as = "DisplayFromStr")]
    pub old_profile_background_custom_emoji_id: i64,
    /// New identifier of chat's profile accent color; -1 if none
    pub new_profile_accent_color_id: i32,
    /// New identifier of the custom emoji; 0 if none
    #[serde_as(as = "DisplayFromStr")]
    pub new_profile_background_custom_emoji_id: i64,
}

/// A video chat was created
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatEventVideoChatCreated {
    /// Identifier of the video chat. The video chat can be received through the method getGroupCall
    pub group_call_id: i32,
}

/// A video chat was ended
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatEventVideoChatEnded {
    /// Identifier of the video chat. The video chat can be received through the method getGroupCall
    pub group_call_id: i32,
}

/// The mute_new_participants setting of a video chat was toggled
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct ChatEventVideoChatMuteNewParticipantsToggled {
    /// New value of the mute_new_participants setting
    pub mute_new_participants: bool,
}

/// A video chat participant was muted or unmuted
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ChatEventVideoChatParticipantIsMutedToggled {
    /// Identifier of the affected group call participant
    pub participant_id: crate::enums::MessageSender,
    /// New value of is_muted
    pub is_muted: bool,
}

/// A video chat participant volume level was changed
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ChatEventVideoChatParticipantVolumeLevelChanged {
    /// Identifier of the affected group call participant
    pub participant_id: crate::enums::MessageSender,
    /// New value of volume_level; 1-20000 in hundreds of percents
    pub volume_level: i32,
}

/// The messages were exported from a private chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageFileTypePrivate {
    /// Name of the other party; may be empty if unrecognized
    pub name: String,
}

/// The messages were exported from a group chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageFileTypeGroup {
    /// Title of the group chat; may be empty if unrecognized
    pub title: String,
}

/// The messages were exported from a chat of unknown type
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageFileTypeUnknown {
}

/// An animation message (GIF-style).
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentAnimation {
    /// Message content; may be null
    pub animation: Option<crate::types::Animation>,
    /// Animation caption
    pub caption: String,
    /// True, if the message is a pinned message with the specified content
    pub is_pinned: bool,
}

/// An audio message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentAudio {
    /// Message content; may be null
    pub audio: Option<crate::types::Audio>,
    /// True, if the message is a pinned message with the specified content
    pub is_pinned: bool,
}

/// A document message (a general file)
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentDocument {
    /// Message content; may be null
    pub document: Option<crate::types::Document>,
    /// True, if the message is a pinned message with the specified content
    pub is_pinned: bool,
}

/// A photo message
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentPhoto {
    /// Message content; may be null
    pub photo: Option<crate::types::Photo>,
    /// Photo caption
    pub caption: String,
    /// True, if the photo is secret
    pub is_secret: bool,
    /// True, if the message is a pinned message with the specified content
    pub is_pinned: bool,
}

/// A video message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentVideo {
    /// Message content; may be null
    pub video: Option<crate::types::Video>,
    /// Video caption
    pub caption: String,
    /// True, if the video is secret
    pub is_secret: bool,
    /// True, if the message is a pinned message with the specified content
    pub is_pinned: bool,
}

/// A video note message
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentVideoNote {
    /// Message content; may be null
    pub video_note: Option<crate::types::VideoNote>,
    /// True, if the message is a pinned message with the specified content
    pub is_pinned: bool,
}

/// A video chat or live stream was started
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentVideoChatStarted {
}

/// A video chat or live stream has ended
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentVideoChatEnded {
}

/// An invitation of participants to a video chat or live stream
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentInviteVideoChatParticipants {
    /// True, if the current user was invited to the video chat or the live stream
    pub is_current_user: bool,
}

/// A chat photo was edited
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentChatChangePhoto {
}

/// A profile photo was suggested to the user
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct PushMessageContentSuggestProfilePhoto {
}

/// A privacy setting for managing whether the user's profile photo is visible
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UserPrivacySettingShowProfilePhoto {
}

/// A privacy setting for managing whether the user's profile audio files are visible
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UserPrivacySettingShowProfileAudio {
}

/// A privacy setting for managing whether the user can receive voice and video messages in private chats; for Telegram Premium users only
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UserPrivacySettingAllowPrivateVoiceAndVideoNoteMessages {
}

/// The profile edit section
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SettingsSectionEditProfile {
    /// Subsection of the section; may be one of
    /// "", "set-photo", "first-name", "last-name", "emoji-status", "bio", "birthday", "change-number", "username",
    /// "your-color", "channel", "add-account", "log-out", "profile-color/profile", "profile-color/profile/add-icons",
    /// "profile-color/profile/use-gift", "profile-color/name", "profile-color/name/add-icons",
    /// "profile-color/name/use-gift", "profile-photo/use-emoji"
    pub subsection: String,
}

/// The link is a link to the My Profile application page
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InternalLinkTypeMyProfilePage {
    /// Section of the page; may be one of
    /// "", "posts", "posts/all-stories", "posts/add-album", "gifts", "archived-posts"
    pub section: String,
}

/// The link is a link to a video chat. Call searchPublicChat with the given chat username, and then joinVideoChat with the given invite hash to process the link
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InternalLinkTypeVideoChat {
    /// Username of the chat with the video chat
    pub chat_username: String,
    /// If non-empty, invite hash to be used to join the video chat without being muted by administrators
    pub invite_hash: String,
    /// True, if the video chat is expected to be a live stream in a channel or a broadcast group
    pub is_live_stream: bool,
}

/// The data is not a file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeNone {
}

/// The file is an animation
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeAnimation {
}

/// The file is an audio file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeAudio {
}

/// The file is a document
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeDocument {
}

/// The file is a video for a live photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeLivePhotoVideo {
}

/// The file is a photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypePhoto {
}

/// The file is a profile photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeProfilePhoto {
}

/// The file was sent to a secret chat (the file type is not known to the server)
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSecret {
}

/// The file is a thumbnail of a file from a secret chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSecretThumbnail {
}

/// The file is a file from Secure storage used for storing Telegram Passport files
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSecure {
}

/// The file is a self-destructing video for a live photo in a private chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSelfDestructingLivePhotoVideo {
}

/// The file is a self-destructing photo in a private chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSelfDestructingPhoto {
}

/// The file is a self-destructing video in a private chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSelfDestructingVideo {
}

/// The file is a self-destructing video note in a private chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSelfDestructingVideoNote {
}

/// The file is a self-destructing voice note in a private chat
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeSelfDestructingVoiceNote {
}

/// The file is a thumbnail of another file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeThumbnail {
}

/// The file type is not yet known
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeUnknown {
}

/// The file is a video
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeVideo {
}

/// The file is a video note
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeVideoNote {
}

/// The file is a voice note
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeVoiceNote {
}

/// The file is a wallpaper or a background pattern
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileTypeWallpaper {
}

/// Contains the storage usage statistics for a specific file type
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct StorageStatisticsByFileType {
    /// File type
    pub file_type: crate::enums::FileType,
    /// Total size of the files, in bytes
    pub size: i64,
    /// Total number of files
    pub count: i32,
}

/// Contains information about the total amount of data that was used to send and receive files
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct NetworkStatisticsEntryFile {
    /// Type of the file the data is part of; pass null if the data isn't related to files
    pub file_type: Option<crate::enums::FileType>,
    /// Type of the network the data was sent through. Call setNetworkType to maintain the actual network type
    pub network_type: crate::enums::NetworkType,
    /// Total number of bytes sent
    pub sent_bytes: i64,
    /// Total number of bytes received
    pub received_bytes: i64,
}

/// Suggests the user to set profile photo
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct SuggestedActionSetProfilePhoto {
}

/// Contains size of downloaded prefix of a file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct FileDownloadedPrefixSize {
    /// The prefix size, in bytes
    pub size: i64,
}

/// An automatically scheduled message with video has been successfully sent after conversion
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateVideoPublished {
    /// Identifier of the chat with the message
    pub chat_id: i64,
    /// Identifier of the sent message
    pub message_id: i64,
}

/// A chat photo was changed
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateChatPhoto {
    /// Chat identifier
    pub chat_id: i64,
    /// The new chat photo; may be null
    pub photo: Option<crate::types::ChatPhotoInfo>,
}

/// A chat video chat state has changed
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateChatVideoChat {
    /// Chat identifier
    pub chat_id: i64,
    /// New value of video_chat
    pub video_chat: crate::types::VideoChat,
}

/// Information about a file was updated
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFile {
    /// New data about the file
    pub file: crate::types::File,
}

/// The file generation process needs to be started by the application. Use setFileGenerationProgress and finishFileGeneration to generate the file
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileGenerationStart {
    /// Unique identifier for the generation process
    #[serde_as(as = "DisplayFromStr")]
    pub generation_id: i64,
    /// The original path specified by the application in inputFileGenerated
    pub original_path: String,
    /// The path to a file that must be created and where the new file must be generated by the application.
    /// If the application has no access to the path, it can use writeGeneratedFilePart to generate the file
    pub destination_path: String,
    /// If the conversion is "#url#", then original_path contains an HTTP/HTTPS URL of a file that must be downloaded by the application.
    /// Otherwise, this is the conversion specified by the application in inputFileGenerated
    pub conversion: String,
}

/// File generation is no longer needed
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileGenerationStop {
    /// Unique identifier for the generation process
    #[serde_as(as = "DisplayFromStr")]
    pub generation_id: i64,
}

/// The state of the file download list has changed
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileDownloads {
    /// Total size of files in the file download list, in bytes
    pub total_size: i64,
    /// Total number of files in the file download list
    pub total_count: i32,
    /// Total downloaded size of files in the file download list, in bytes
    pub downloaded_size: i64,
}

/// A file was added to the file download list. This update is sent only after file download list is loaded for the first time
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileAddedToDownloads {
    /// The added file download
    pub file_download: crate::types::FileDownload,
    /// New number of being downloaded and recently downloaded files found
    pub counts: crate::types::DownloadedFileCounts,
}

/// A file download was changed. This update is sent only after file download list is loaded for the first time
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileDownload {
    /// File identifier
    pub file_id: i32,
    /// Point in time (Unix timestamp) when the file downloading was completed; 0 if the file downloading isn't completed
    pub complete_date: i32,
    /// True, if downloading of the file is paused
    pub is_paused: bool,
    /// New number of being downloaded and recently downloaded files found
    pub counts: crate::types::DownloadedFileCounts,
}

/// A file was removed from the file download list. This update is sent only after file download list is loaded for the first time
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileRemovedFromDownloads {
    /// File identifier
    pub file_id: i32,
    /// New number of being downloaded and recently downloaded files found
    pub counts: crate::types::DownloadedFileCounts,
}

/// The list of saved animations was updated
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateSavedAnimations {
    /// The new list of file identifiers of saved animations
    pub animation_ids: Vec<i32>,
}

/// The list of supported accent colors for user profiles has changed
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateProfileAccentColors {
    /// Information about supported colors
    pub colors: Vec<crate::types::ProfileAccentColor>,
    /// The list of accent color identifiers, which can be set through setProfileAccentColor and setChatProfileAccentColor. The colors must be shown in the specified order
    pub available_accent_color_ids: Vec<i32>,
}

/// The parameters of animation search through getOption("animation_search_bot_username") bot have changed
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateAnimationSearchParameters {
    /// Name of the animation search provider
    pub provider: String,
    /// The new list of emojis suggested for searching
    pub emojis: Vec<String>,
}

/// The log is written to a file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LogStreamFile {
    /// Path to the file to where the internal TDLib log will be written
    pub path: String,
    /// The maximum size of the file to where the internal TDLib log is written before the file will automatically be rotated, in bytes
    pub max_file_size: i64,
    /// Pass true to additionally redirect stderr to the log file. Ignored on Windows
    pub redirect_stderr: bool,
}

