#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};


/// A file generated by the application. The application must handle updates updateFileGenerationStart and updateFileGenerationStop to generate the file when asked by TDLib
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct InputFileGenerated {
    /// Local path to a file from which the file is generated. The path doesn't have to be a valid path and is used by TDLib only to detect name and MIME type of the generated file
    pub original_path: String,
    /// String specifying the conversion applied to the original file; must be persistent across application restarts. Conversions beginning with '#' are reserved for internal TDLib usage
    pub conversion: String,
    /// Expected size of the generated file, in bytes; pass 0 if unknown
    pub expected_size: i64,
}
