#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};

/// Represents a local file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct LocalFile {
    /// Local path to the locally available file part; may be empty
    pub path: String,
    /// True, if it is possible to download or generate the file
    pub can_be_downloaded: bool,
    /// True, if the file can be deleted
    pub can_be_deleted: bool,
    /// True, if the file is currently being downloaded (or a local copy is being generated by some other means)
    pub is_downloading_active: bool,
    /// True, if the local copy is fully available
    pub is_downloading_completed: bool,
    /// Download will be started from this offset. downloaded_prefix_size is calculated from this offset
    pub download_offset: i64,
    /// If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix in bytes
    pub downloaded_prefix_size: i64,
    /// Total downloaded file size, in bytes. Can be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage
    pub downloaded_size: i64,
}
