#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};


/// A stake dice message. The dice value is randomly generated by the server
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageStakeDice {
    /// The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
    pub initial_state: Option<crate::enums::DiceStickers>,
    /// The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
    pub final_state: Option<crate::enums::DiceStickers>,
    /// The dice value. If the value is 0, then the dice don't have final state yet
    pub value: i32,
    /// The Toncoin amount that was staked; in the smallest units of the currency
    pub stake_toncoin_amount: i64,
    /// The Toncoin amount that was gained from the roll; in the smallest units of the currency; -1 if the dice don't have final state yet
    pub prize_toncoin_amount: i64,
}
