#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};

/// A dice message. The dice value is randomly generated by the server
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct MessageDice {
    /// The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
    pub initial_state: Option<crate::enums::DiceStickers>,
    /// The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
    pub final_state: Option<crate::enums::DiceStickers>,
    /// Emoji on which the dice throw animation is based
    pub emoji: String,
    /// The dice value. If the value is 0, then the dice don't have final state yet
    pub value: i32,
    /// Number of frame after which a success animation like a shower of confetti needs to be shown on updateMessageSendSucceeded
    pub success_animation_frame_number: i32,
}
