#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};

/// Represents a remote file
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct RemoteFile {
    /// Remote file identifier; may be empty. Can be used by the current user across application restarts or even from other devices. Uniquely identifies a file, but a file can have a lot of different valid identifiers.
    /// If the identifier starts with "http:" or "https:", it represents the HTTP URL of the file. TDLib is currently unable to download files if only their URL is known.
    /// If downloadFile/addFileToDownloads is called on such a file or if it is sent to a secret chat, TDLib starts a file generation process by sending updateFileGenerationStart to the application with the HTTP URL in the original_path and "#url#" as the conversion string.
    /// Application must generate the file by downloading it to the specified location
    pub id: String,
    /// Unique file identifier; may be empty if unknown. The unique file identifier which is the same for the same file even for different users and is persistent over time
    pub unique_id: String,
    /// True, if the file is currently being uploaded (or a remote copy is being generated by some other means)
    pub is_uploading_active: bool,
    /// True, if a remote copy is fully available
    pub is_uploading_completed: bool,
    /// Size of the remote available part of the file, in bytes; 0 if unknown
    pub uploaded_size: i64,
}
