#[allow(clippy::all)]
use serde::{Deserialize, Serialize};
use serde_with::{serde_as, DisplayFromStr};


/// The file generation process needs to be started by the application. Use setFileGenerationProgress and finishFileGeneration to generate the file
#[serde_as]
#[derive(Clone, Debug, Default, PartialEq, Deserialize, Serialize)]
pub struct UpdateFileGenerationStart {
    /// Unique identifier for the generation process
    #[serde_as(as = "DisplayFromStr")]
    pub generation_id: i64,
    /// The original path specified by the application in inputFileGenerated
    pub original_path: String,
    /// The path to a file that must be created and where the new file must be generated by the application.
    /// If the application has no access to the path, it can use writeGeneratedFilePart to generate the file
    pub destination_path: String,
    /// If the conversion is "#url#" than original_path contains an HTTP/HTTPS URL of a file that must be downloaded by the application.
    /// Otherwise, this is the conversion specified by the application in inputFileGenerated
    pub conversion: String,
}
