//!
//! TDLib `file` domain enums.
//!
//! Types, enums, and functions for local and remote files, photos, audio, videos, and documents.
//!

#[allow(clippy::all)]
use serde::{Deserialize, Serialize};

/// TDLib `LocalFile` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum LocalFile {
    /// Represents a local file
    #[serde(rename(serialize = "localFile", deserialize = "localFile"))]
    LocalFile(Box<crate::types::LocalFile>),
}

impl LocalFile {
    /// Convenience constructor to create a [`LocalFile::LocalFile`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn local_file(val: crate::types::LocalFile) -> Self {
        Self::LocalFile(Box::new(val))
    }

}

/// Converts a [`crate::types::LocalFile`] into [`LocalFile`].
impl From<crate::types::LocalFile> for LocalFile {
    fn from(val: crate::types::LocalFile) -> Self {
        Self::LocalFile(Box::new(val))
    }
}

/// TDLib `RemoteFile` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum RemoteFile {
    /// Represents a remote file
    #[serde(rename(serialize = "remoteFile", deserialize = "remoteFile"))]
    RemoteFile(Box<crate::types::RemoteFile>),
}

impl RemoteFile {
    /// Convenience constructor to create a [`RemoteFile::RemoteFile`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn remote_file(val: crate::types::RemoteFile) -> Self {
        Self::RemoteFile(Box::new(val))
    }

}

/// Converts a [`crate::types::RemoteFile`] into [`RemoteFile`].
impl From<crate::types::RemoteFile> for RemoteFile {
    fn from(val: crate::types::RemoteFile) -> Self {
        Self::RemoteFile(Box::new(val))
    }
}

/// TDLib `File` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum File {
    /// Represents a file
    #[serde(rename(serialize = "file", deserialize = "file"))]
    File(Box<crate::types::File>),
}

impl File {
    /// Convenience constructor to create a [`File::File`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn file(val: crate::types::File) -> Self {
        Self::File(Box::new(val))
    }

}

/// Converts a [`crate::types::File`] into [`File`].
impl From<crate::types::File> for File {
    fn from(val: crate::types::File) -> Self {
        Self::File(Box::new(val))
    }
}

/// Points to a file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputFile {
    /// A file defined by its unique identifier
    #[serde(rename(serialize = "inputFileId", deserialize = "inputFileId"))]
    Id(Box<crate::types::InputFileId>),
    /// A file defined by its remote identifier. The remote identifier is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib.
    /// For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application
    #[serde(rename(serialize = "inputFileRemote", deserialize = "inputFileRemote"))]
    Remote(Box<crate::types::InputFileRemote>),
    /// A file defined by a local path
    #[serde(rename(serialize = "inputFileLocal", deserialize = "inputFileLocal"))]
    Local(Box<crate::types::InputFileLocal>),
    /// A file generated by the application. The application must handle updates updateFileGenerationStart and updateFileGenerationStop to generate the file when asked by TDLib
    #[serde(rename(serialize = "inputFileGenerated", deserialize = "inputFileGenerated"))]
    Generated(Box<crate::types::InputFileGenerated>),
}

impl InputFile {
    /// Convenience constructor to create a [`InputFile::Id`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn id(val: crate::types::InputFileId) -> Self {
        Self::Id(Box::new(val))
    }

    /// Convenience constructor to create a [`InputFile::Remote`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn remote(val: crate::types::InputFileRemote) -> Self {
        Self::Remote(Box::new(val))
    }

    /// Convenience constructor to create a [`InputFile::Local`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn local(val: crate::types::InputFileLocal) -> Self {
        Self::Local(Box::new(val))
    }

    /// Convenience constructor to create a [`InputFile::Generated`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn generated(val: crate::types::InputFileGenerated) -> Self {
        Self::Generated(Box::new(val))
    }

}

/// Converts a [`crate::types::InputFileId`] into [`InputFile`].
impl From<crate::types::InputFileId> for InputFile {
    fn from(val: crate::types::InputFileId) -> Self {
        Self::Id(Box::new(val))
    }
}

/// Converts a [`crate::types::InputFileRemote`] into [`InputFile`].
impl From<crate::types::InputFileRemote> for InputFile {
    fn from(val: crate::types::InputFileRemote) -> Self {
        Self::Remote(Box::new(val))
    }
}

/// Converts a [`crate::types::InputFileLocal`] into [`InputFile`].
impl From<crate::types::InputFileLocal> for InputFile {
    fn from(val: crate::types::InputFileLocal) -> Self {
        Self::Local(Box::new(val))
    }
}

/// Converts a [`crate::types::InputFileGenerated`] into [`InputFile`].
impl From<crate::types::InputFileGenerated> for InputFile {
    fn from(val: crate::types::InputFileGenerated) -> Self {
        Self::Generated(Box::new(val))
    }
}

/// TDLib `PhotoSize` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum PhotoSize {
    /// Describes an image in JPEG format
    #[serde(rename(serialize = "photoSize", deserialize = "photoSize"))]
    PhotoSize(Box<crate::types::PhotoSize>),
}

impl PhotoSize {
    /// Convenience constructor to create a [`PhotoSize::PhotoSize`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn photo_size(val: crate::types::PhotoSize) -> Self {
        Self::PhotoSize(Box::new(val))
    }

}

/// Converts a [`crate::types::PhotoSize`] into [`PhotoSize`].
impl From<crate::types::PhotoSize> for PhotoSize {
    fn from(val: crate::types::PhotoSize) -> Self {
        Self::PhotoSize(Box::new(val))
    }
}

/// TDLib `Minithumbnail` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Minithumbnail {
    /// Thumbnail image of a very poor quality and low resolution
    #[serde(rename(serialize = "minithumbnail", deserialize = "minithumbnail"))]
    Minithumbnail(Box<crate::types::Minithumbnail>),
}

impl Minithumbnail {
    /// Convenience constructor to create a [`Minithumbnail::Minithumbnail`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn minithumbnail(val: crate::types::Minithumbnail) -> Self {
        Self::Minithumbnail(Box::new(val))
    }

}

/// Converts a [`crate::types::Minithumbnail`] into [`Minithumbnail`].
impl From<crate::types::Minithumbnail> for Minithumbnail {
    fn from(val: crate::types::Minithumbnail) -> Self {
        Self::Minithumbnail(Box::new(val))
    }
}

/// Describes format of a thumbnail
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ThumbnailFormat {
    /// The thumbnail is in JPEG format
    #[serde(rename(serialize = "thumbnailFormatJpeg", deserialize = "thumbnailFormatJpeg"))]
    Jpeg,
    /// The thumbnail is in static GIF format. It will be used only for some bot inline query results
    #[serde(rename(serialize = "thumbnailFormatGif", deserialize = "thumbnailFormatGif"))]
    Gif,
    /// The thumbnail is in MPEG4 format. It will be used only for some animations and videos
    #[serde(rename(serialize = "thumbnailFormatMpeg4", deserialize = "thumbnailFormatMpeg4"))]
    Mpeg4,
    /// The thumbnail is in PNG format. It will be used only for background patterns
    #[serde(rename(serialize = "thumbnailFormatPng", deserialize = "thumbnailFormatPng"))]
    Png,
    /// The thumbnail is in TGS format. It will be used only for sticker sets
    #[serde(rename(serialize = "thumbnailFormatTgs", deserialize = "thumbnailFormatTgs"))]
    Tgs,
    /// The thumbnail is in WEBM format. It will be used only for sticker sets
    #[serde(rename(serialize = "thumbnailFormatWebm", deserialize = "thumbnailFormatWebm"))]
    Webm,
    /// The thumbnail is in WEBP format. It will be used only for some stickers and sticker sets
    #[serde(rename(serialize = "thumbnailFormatWebp", deserialize = "thumbnailFormatWebp"))]
    Webp,
}

/// TDLib `Thumbnail` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Thumbnail {
    /// Represents a thumbnail
    #[serde(rename(serialize = "thumbnail", deserialize = "thumbnail"))]
    Thumbnail(Box<crate::types::Thumbnail>),
}

impl Thumbnail {
    /// Convenience constructor to create a [`Thumbnail::Thumbnail`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn thumbnail(val: crate::types::Thumbnail) -> Self {
        Self::Thumbnail(Box::new(val))
    }

}

/// Converts a [`crate::types::Thumbnail`] into [`Thumbnail`].
impl From<crate::types::Thumbnail> for Thumbnail {
    fn from(val: crate::types::Thumbnail) -> Self {
        Self::Thumbnail(Box::new(val))
    }
}

/// TDLib `Animation` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Animation {
    /// Describes an animation file. The animation must be encoded in GIF or MPEG4 format
    #[serde(rename(serialize = "animation", deserialize = "animation"))]
    Animation(Box<crate::types::Animation>),
}

impl Animation {
    /// Convenience constructor to create a [`Animation::Animation`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn animation(val: crate::types::Animation) -> Self {
        Self::Animation(Box::new(val))
    }

}

/// Converts a [`crate::types::Animation`] into [`Animation`].
impl From<crate::types::Animation> for Animation {
    fn from(val: crate::types::Animation) -> Self {
        Self::Animation(Box::new(val))
    }
}

/// TDLib `Audio` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Audio {
    /// Describes an audio file. Audio is usually in MP3 or M4A format
    #[serde(rename(serialize = "audio", deserialize = "audio"))]
    Audio(Box<crate::types::Audio>),
}

impl Audio {
    /// Convenience constructor to create a [`Audio::Audio`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn audio(val: crate::types::Audio) -> Self {
        Self::Audio(Box::new(val))
    }

}

/// Converts a [`crate::types::Audio`] into [`Audio`].
impl From<crate::types::Audio> for Audio {
    fn from(val: crate::types::Audio) -> Self {
        Self::Audio(Box::new(val))
    }
}

/// TDLib `Audios` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Audios {
    /// Contains a list of audio files
    #[serde(rename(serialize = "audios", deserialize = "audios"))]
    Audios(Box<crate::types::Audios>),
}

impl Audios {
    /// Convenience constructor to create a [`Audios::Audios`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn audios(val: crate::types::Audios) -> Self {
        Self::Audios(Box::new(val))
    }

}

/// Converts a [`crate::types::Audios`] into [`Audios`].
impl From<crate::types::Audios> for Audios {
    fn from(val: crate::types::Audios) -> Self {
        Self::Audios(Box::new(val))
    }
}

/// TDLib `Document` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Document {
    /// Describes a document of any type
    #[serde(rename(serialize = "document", deserialize = "document"))]
    Document(Box<crate::types::Document>),
}

impl Document {
    /// Convenience constructor to create a [`Document::Document`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn document(val: crate::types::Document) -> Self {
        Self::Document(Box::new(val))
    }

}

/// Converts a [`crate::types::Document`] into [`Document`].
impl From<crate::types::Document> for Document {
    fn from(val: crate::types::Document) -> Self {
        Self::Document(Box::new(val))
    }
}

/// TDLib `Photo` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Photo {
    /// Describes a photo
    #[serde(rename(serialize = "photo", deserialize = "photo"))]
    Photo(Box<crate::types::Photo>),
}

impl Photo {
    /// Convenience constructor to create a [`Photo::Photo`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn photo(val: crate::types::Photo) -> Self {
        Self::Photo(Box::new(val))
    }

}

/// Converts a [`crate::types::Photo`] into [`Photo`].
impl From<crate::types::Photo> for Photo {
    fn from(val: crate::types::Photo) -> Self {
        Self::Photo(Box::new(val))
    }
}

/// TDLib `Video` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Video {
    /// Describes a video file
    #[serde(rename(serialize = "video", deserialize = "video"))]
    Video(Box<crate::types::Video>),
}

impl Video {
    /// Convenience constructor to create a [`Video::Video`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn video(val: crate::types::Video) -> Self {
        Self::Video(Box::new(val))
    }

}

/// Converts a [`crate::types::Video`] into [`Video`].
impl From<crate::types::Video> for Video {
    fn from(val: crate::types::Video) -> Self {
        Self::Video(Box::new(val))
    }
}

/// TDLib `VideoNote` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum VideoNote {
    /// Describes a video note. The video must be equal in width and height, cropped to a circle, and stored in MPEG4 format
    #[serde(rename(serialize = "videoNote", deserialize = "videoNote"))]
    VideoNote(Box<crate::types::VideoNote>),
}

impl VideoNote {
    /// Convenience constructor to create a [`VideoNote::VideoNote`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn video_note(val: crate::types::VideoNote) -> Self {
        Self::VideoNote(Box::new(val))
    }

}

/// Converts a [`crate::types::VideoNote`] into [`VideoNote`].
impl From<crate::types::VideoNote> for VideoNote {
    fn from(val: crate::types::VideoNote) -> Self {
        Self::VideoNote(Box::new(val))
    }
}

/// TDLib `AlternativeVideo` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum AlternativeVideo {
    /// Describes an alternative re-encoded quality of a video file
    #[serde(rename(serialize = "alternativeVideo", deserialize = "alternativeVideo"))]
    AlternativeVideo(Box<crate::types::AlternativeVideo>),
}

impl AlternativeVideo {
    /// Convenience constructor to create a [`AlternativeVideo::AlternativeVideo`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn alternative_video(val: crate::types::AlternativeVideo) -> Self {
        Self::AlternativeVideo(Box::new(val))
    }

}

/// Converts a [`crate::types::AlternativeVideo`] into [`AlternativeVideo`].
impl From<crate::types::AlternativeVideo> for AlternativeVideo {
    fn from(val: crate::types::AlternativeVideo) -> Self {
        Self::AlternativeVideo(Box::new(val))
    }
}

/// TDLib `ProfilePhoto` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ProfilePhoto {
    /// Describes a user profile photo
    #[serde(rename(serialize = "profilePhoto", deserialize = "profilePhoto"))]
    ProfilePhoto(Box<crate::types::ProfilePhoto>),
}

impl ProfilePhoto {
    /// Convenience constructor to create a [`ProfilePhoto::ProfilePhoto`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn profile_photo(val: crate::types::ProfilePhoto) -> Self {
        Self::ProfilePhoto(Box::new(val))
    }

}

/// Converts a [`crate::types::ProfilePhoto`] into [`ProfilePhoto`].
impl From<crate::types::ProfilePhoto> for ProfilePhoto {
    fn from(val: crate::types::ProfilePhoto) -> Self {
        Self::ProfilePhoto(Box::new(val))
    }
}

/// TDLib `ChatPhotoInfo` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ChatPhotoInfo {
    /// Contains basic information about the photo of a chat
    #[serde(rename(serialize = "chatPhotoInfo", deserialize = "chatPhotoInfo"))]
    ChatPhotoInfo(Box<crate::types::ChatPhotoInfo>),
}

impl ChatPhotoInfo {
    /// Convenience constructor to create a [`ChatPhotoInfo::ChatPhotoInfo`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn chat_photo_info(val: crate::types::ChatPhotoInfo) -> Self {
        Self::ChatPhotoInfo(Box::new(val))
    }

}

/// Converts a [`crate::types::ChatPhotoInfo`] into [`ChatPhotoInfo`].
impl From<crate::types::ChatPhotoInfo> for ChatPhotoInfo {
    fn from(val: crate::types::ChatPhotoInfo) -> Self {
        Self::ChatPhotoInfo(Box::new(val))
    }
}

/// Describes a tab shown in a user or a chat profile
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ProfileTab {
    /// A tab with stories posted by the user or the channel chat and saved to profile
    #[serde(rename(serialize = "profileTabPosts", deserialize = "profileTabPosts"))]
    Posts,
    /// A tab with gifts received by the user or the channel chat
    #[serde(rename(serialize = "profileTabGifts", deserialize = "profileTabGifts"))]
    Gifts,
    /// A tab with photos and videos posted by the channel
    #[serde(rename(serialize = "profileTabMedia", deserialize = "profileTabMedia"))]
    Media,
    /// A tab with documents posted by the channel
    #[serde(rename(serialize = "profileTabFiles", deserialize = "profileTabFiles"))]
    Files,
    /// A tab with messages posted by the channel and containing links
    #[serde(rename(serialize = "profileTabLinks", deserialize = "profileTabLinks"))]
    Links,
    /// A tab with audio messages posted by the channel
    #[serde(rename(serialize = "profileTabMusic", deserialize = "profileTabMusic"))]
    Music,
    /// A tab with voice notes posted by the channel
    #[serde(rename(serialize = "profileTabVoice", deserialize = "profileTabVoice"))]
    Voice,
    /// A tab with animations posted by the channel
    #[serde(rename(serialize = "profileTabGifs", deserialize = "profileTabGifs"))]
    Gifs,
}

/// TDLib `ChatPhoto` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ChatPhoto {
    /// Describes a chat or user profile photo
    #[serde(rename(serialize = "chatPhoto", deserialize = "chatPhoto"))]
    ChatPhoto(Box<crate::types::ChatPhoto>),
}

impl ChatPhoto {
    /// Convenience constructor to create a [`ChatPhoto::ChatPhoto`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn chat_photo(val: crate::types::ChatPhoto) -> Self {
        Self::ChatPhoto(Box::new(val))
    }

}

/// Converts a [`crate::types::ChatPhoto`] into [`ChatPhoto`].
impl From<crate::types::ChatPhoto> for ChatPhoto {
    fn from(val: crate::types::ChatPhoto) -> Self {
        Self::ChatPhoto(Box::new(val))
    }
}

/// TDLib `ChatPhotos` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ChatPhotos {
    /// Contains a list of chat or user profile photos
    #[serde(rename(serialize = "chatPhotos", deserialize = "chatPhotos"))]
    ChatPhotos(Box<crate::types::ChatPhotos>),
}

impl ChatPhotos {
    /// Convenience constructor to create a [`ChatPhotos::ChatPhotos`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn chat_photos(val: crate::types::ChatPhotos) -> Self {
        Self::ChatPhotos(Box::new(val))
    }

}

/// Converts a [`crate::types::ChatPhotos`] into [`ChatPhotos`].
impl From<crate::types::ChatPhotos> for ChatPhotos {
    fn from(val: crate::types::ChatPhotos) -> Self {
        Self::ChatPhotos(Box::new(val))
    }
}

/// Describes a photo to be set as a user profile or chat photo
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputChatPhoto {
    /// A previously used profile photo of the current user
    #[serde(rename(serialize = "inputChatPhotoPrevious", deserialize = "inputChatPhotoPrevious"))]
    Previous(Box<crate::types::InputChatPhotoPrevious>),
    /// A static photo in JPEG format
    #[serde(rename(serialize = "inputChatPhotoStatic", deserialize = "inputChatPhotoStatic"))]
    Static(Box<crate::types::InputChatPhotoStatic>),
    /// An animation in MPEG4 format; must be square, at most 10 seconds long, have width between 160 and 1280 and be at most 2MB in size
    #[serde(rename(serialize = "inputChatPhotoAnimation", deserialize = "inputChatPhotoAnimation"))]
    Animation(Box<crate::types::InputChatPhotoAnimation>),
    /// A sticker on a custom background
    #[serde(rename(serialize = "inputChatPhotoSticker", deserialize = "inputChatPhotoSticker"))]
    Sticker(Box<crate::types::InputChatPhotoSticker>),
}

impl InputChatPhoto {
    /// Convenience constructor to create a [`InputChatPhoto::Previous`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn previous(val: crate::types::InputChatPhotoPrevious) -> Self {
        Self::Previous(Box::new(val))
    }

    /// Convenience constructor to create a [`InputChatPhoto::Static`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn r#static(val: crate::types::InputChatPhotoStatic) -> Self {
        Self::Static(Box::new(val))
    }

    /// Convenience constructor to create a [`InputChatPhoto::Animation`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn animation(val: crate::types::InputChatPhotoAnimation) -> Self {
        Self::Animation(Box::new(val))
    }

    /// Convenience constructor to create a [`InputChatPhoto::Sticker`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn sticker(val: crate::types::InputChatPhotoSticker) -> Self {
        Self::Sticker(Box::new(val))
    }

}

/// Converts a [`crate::types::InputChatPhotoPrevious`] into [`InputChatPhoto`].
impl From<crate::types::InputChatPhotoPrevious> for InputChatPhoto {
    fn from(val: crate::types::InputChatPhotoPrevious) -> Self {
        Self::Previous(Box::new(val))
    }
}

/// Converts a [`crate::types::InputChatPhotoStatic`] into [`InputChatPhoto`].
impl From<crate::types::InputChatPhotoStatic> for InputChatPhoto {
    fn from(val: crate::types::InputChatPhotoStatic) -> Self {
        Self::Static(Box::new(val))
    }
}

/// Converts a [`crate::types::InputChatPhotoAnimation`] into [`InputChatPhoto`].
impl From<crate::types::InputChatPhotoAnimation> for InputChatPhoto {
    fn from(val: crate::types::InputChatPhotoAnimation) -> Self {
        Self::Animation(Box::new(val))
    }
}

/// Converts a [`crate::types::InputChatPhotoSticker`] into [`InputChatPhoto`].
impl From<crate::types::InputChatPhotoSticker> for InputChatPhoto {
    fn from(val: crate::types::InputChatPhotoSticker) -> Self {
        Self::Sticker(Box::new(val))
    }
}

/// TDLib `ProfileAccentColors` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ProfileAccentColors {
    /// Contains information about supported accent colors for user profile photo background in RGB format
    #[serde(rename(serialize = "profileAccentColors", deserialize = "profileAccentColors"))]
    ProfileAccentColors(Box<crate::types::ProfileAccentColors>),
}

impl ProfileAccentColors {
    /// Convenience constructor to create a [`ProfileAccentColors::ProfileAccentColors`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn profile_accent_colors(val: crate::types::ProfileAccentColors) -> Self {
        Self::ProfileAccentColors(Box::new(val))
    }

}

/// Converts a [`crate::types::ProfileAccentColors`] into [`ProfileAccentColors`].
impl From<crate::types::ProfileAccentColors> for ProfileAccentColors {
    fn from(val: crate::types::ProfileAccentColors) -> Self {
        Self::ProfileAccentColors(Box::new(val))
    }
}

/// TDLib `ProfileAccentColor` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum ProfileAccentColor {
    /// Contains information about supported accent color for user profile photo background
    #[serde(rename(serialize = "profileAccentColor", deserialize = "profileAccentColor"))]
    ProfileAccentColor(Box<crate::types::ProfileAccentColor>),
}

impl ProfileAccentColor {
    /// Convenience constructor to create a [`ProfileAccentColor::ProfileAccentColor`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn profile_accent_color(val: crate::types::ProfileAccentColor) -> Self {
        Self::ProfileAccentColor(Box::new(val))
    }

}

/// Converts a [`crate::types::ProfileAccentColor`] into [`ProfileAccentColor`].
impl From<crate::types::ProfileAccentColor> for ProfileAccentColor {
    fn from(val: crate::types::ProfileAccentColor) -> Self {
        Self::ProfileAccentColor(Box::new(val))
    }
}

/// TDLib `VideoMessageAdvertisement` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum VideoMessageAdvertisement {
    /// Describes an advertisement to be shown while a video from a message is watched
    #[serde(rename(serialize = "videoMessageAdvertisement", deserialize = "videoMessageAdvertisement"))]
    VideoMessageAdvertisement(Box<crate::types::VideoMessageAdvertisement>),
}

impl VideoMessageAdvertisement {
    /// Convenience constructor to create a [`VideoMessageAdvertisement::VideoMessageAdvertisement`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn video_message_advertisement(val: crate::types::VideoMessageAdvertisement) -> Self {
        Self::VideoMessageAdvertisement(Box::new(val))
    }

}

/// Converts a [`crate::types::VideoMessageAdvertisement`] into [`VideoMessageAdvertisement`].
impl From<crate::types::VideoMessageAdvertisement> for VideoMessageAdvertisement {
    fn from(val: crate::types::VideoMessageAdvertisement) -> Self {
        Self::VideoMessageAdvertisement(Box::new(val))
    }
}

/// TDLib `VideoMessageAdvertisements` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum VideoMessageAdvertisements {
    /// Contains a list of advertisements to be shown while a video from a message is watched
    #[serde(rename(serialize = "videoMessageAdvertisements", deserialize = "videoMessageAdvertisements"))]
    VideoMessageAdvertisements(Box<crate::types::VideoMessageAdvertisements>),
}

impl VideoMessageAdvertisements {
    /// Convenience constructor to create a [`VideoMessageAdvertisements::VideoMessageAdvertisements`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn video_message_advertisements(val: crate::types::VideoMessageAdvertisements) -> Self {
        Self::VideoMessageAdvertisements(Box::new(val))
    }

}

/// Converts a [`crate::types::VideoMessageAdvertisements`] into [`VideoMessageAdvertisements`].
impl From<crate::types::VideoMessageAdvertisements> for VideoMessageAdvertisements {
    fn from(val: crate::types::VideoMessageAdvertisements) -> Self {
        Self::VideoMessageAdvertisements(Box::new(val))
    }
}

/// TDLib `FileDownload` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum FileDownload {
    /// Describes a file added to file download list
    #[serde(rename(serialize = "fileDownload", deserialize = "fileDownload"))]
    FileDownload(Box<crate::types::FileDownload>),
}

impl FileDownload {
    /// Convenience constructor to create a [`FileDownload::FileDownload`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn file_download(val: crate::types::FileDownload) -> Self {
        Self::FileDownload(Box::new(val))
    }

}

/// Converts a [`crate::types::FileDownload`] into [`FileDownload`].
impl From<crate::types::FileDownload> for FileDownload {
    fn from(val: crate::types::FileDownload) -> Self {
        Self::FileDownload(Box::new(val))
    }
}

/// TDLib `DownloadedFileCounts` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum DownloadedFileCounts {
    /// Contains number of being downloaded and recently downloaded files found
    #[serde(rename(serialize = "downloadedFileCounts", deserialize = "downloadedFileCounts"))]
    DownloadedFileCounts(Box<crate::types::DownloadedFileCounts>),
}

impl DownloadedFileCounts {
    /// Convenience constructor to create a [`DownloadedFileCounts::DownloadedFileCounts`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn downloaded_file_counts(val: crate::types::DownloadedFileCounts) -> Self {
        Self::DownloadedFileCounts(Box::new(val))
    }

}

/// Converts a [`crate::types::DownloadedFileCounts`] into [`DownloadedFileCounts`].
impl From<crate::types::DownloadedFileCounts> for DownloadedFileCounts {
    fn from(val: crate::types::DownloadedFileCounts) -> Self {
        Self::DownloadedFileCounts(Box::new(val))
    }
}

/// TDLib `FoundFileDownloads` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum FoundFileDownloads {
    /// Contains a list of downloaded files, found by a search
    #[serde(rename(serialize = "foundFileDownloads", deserialize = "foundFileDownloads"))]
    FoundFileDownloads(Box<crate::types::FoundFileDownloads>),
}

impl FoundFileDownloads {
    /// Convenience constructor to create a [`FoundFileDownloads::FoundFileDownloads`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn found_file_downloads(val: crate::types::FoundFileDownloads) -> Self {
        Self::FoundFileDownloads(Box::new(val))
    }

}

/// Converts a [`crate::types::FoundFileDownloads`] into [`FoundFileDownloads`].
impl From<crate::types::FoundFileDownloads> for FoundFileDownloads {
    fn from(val: crate::types::FoundFileDownloads) -> Self {
        Self::FoundFileDownloads(Box::new(val))
    }
}

/// TDLib `VideoChat` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum VideoChat {
    /// Describes a video chat, i.e. a group call bound to a chat
    #[serde(rename(serialize = "videoChat", deserialize = "videoChat"))]
    VideoChat(Box<crate::types::VideoChat>),
}

impl VideoChat {
    /// Convenience constructor to create a [`VideoChat::VideoChat`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn video_chat(val: crate::types::VideoChat) -> Self {
        Self::VideoChat(Box::new(val))
    }

}

/// Converts a [`crate::types::VideoChat`] into [`VideoChat`].
impl From<crate::types::VideoChat> for VideoChat {
    fn from(val: crate::types::VideoChat) -> Self {
        Self::VideoChat(Box::new(val))
    }
}

/// TDLib `DatedFile` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum DatedFile {
    /// File with the date it was uploaded
    #[serde(rename(serialize = "datedFile", deserialize = "datedFile"))]
    DatedFile(Box<crate::types::DatedFile>),
}

impl DatedFile {
    /// Convenience constructor to create a [`DatedFile::DatedFile`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn dated_file(val: crate::types::DatedFile) -> Self {
        Self::DatedFile(Box::new(val))
    }

}

/// Converts a [`crate::types::DatedFile`] into [`DatedFile`].
impl From<crate::types::DatedFile> for DatedFile {
    fn from(val: crate::types::DatedFile) -> Self {
        Self::DatedFile(Box::new(val))
    }
}

/// TDLib `IdentityDocument` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum IdentityDocument {
    /// An identity document
    #[serde(rename(serialize = "identityDocument", deserialize = "identityDocument"))]
    IdentityDocument(Box<crate::types::IdentityDocument>),
}

impl IdentityDocument {
    /// Convenience constructor to create a [`IdentityDocument::IdentityDocument`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn identity_document(val: crate::types::IdentityDocument) -> Self {
        Self::IdentityDocument(Box::new(val))
    }

}

/// Converts a [`crate::types::IdentityDocument`] into [`IdentityDocument`].
impl From<crate::types::IdentityDocument> for IdentityDocument {
    fn from(val: crate::types::IdentityDocument) -> Self {
        Self::IdentityDocument(Box::new(val))
    }
}

/// TDLib `InputIdentityDocument` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputIdentityDocument {
    /// An identity document to be saved to Telegram Passport
    #[serde(rename(serialize = "inputIdentityDocument", deserialize = "inputIdentityDocument"))]
    InputIdentityDocument(Box<crate::types::InputIdentityDocument>),
}

impl InputIdentityDocument {
    /// Convenience constructor to create a [`InputIdentityDocument::InputIdentityDocument`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_identity_document(val: crate::types::InputIdentityDocument) -> Self {
        Self::InputIdentityDocument(Box::new(val))
    }

}

/// Converts a [`crate::types::InputIdentityDocument`] into [`InputIdentityDocument`].
impl From<crate::types::InputIdentityDocument> for InputIdentityDocument {
    fn from(val: crate::types::InputIdentityDocument) -> Self {
        Self::InputIdentityDocument(Box::new(val))
    }
}

/// TDLib `PersonalDocument` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum PersonalDocument {
    /// A personal document, containing some information about a user
    #[serde(rename(serialize = "personalDocument", deserialize = "personalDocument"))]
    PersonalDocument(Box<crate::types::PersonalDocument>),
}

impl PersonalDocument {
    /// Convenience constructor to create a [`PersonalDocument::PersonalDocument`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn personal_document(val: crate::types::PersonalDocument) -> Self {
        Self::PersonalDocument(Box::new(val))
    }

}

/// Converts a [`crate::types::PersonalDocument`] into [`PersonalDocument`].
impl From<crate::types::PersonalDocument> for PersonalDocument {
    fn from(val: crate::types::PersonalDocument) -> Self {
        Self::PersonalDocument(Box::new(val))
    }
}

/// TDLib `InputPersonalDocument` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputPersonalDocument {
    /// A personal document to be saved to Telegram Passport
    #[serde(rename(serialize = "inputPersonalDocument", deserialize = "inputPersonalDocument"))]
    InputPersonalDocument(Box<crate::types::InputPersonalDocument>),
}

impl InputPersonalDocument {
    /// Convenience constructor to create a [`InputPersonalDocument::InputPersonalDocument`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_personal_document(val: crate::types::InputPersonalDocument) -> Self {
        Self::InputPersonalDocument(Box::new(val))
    }

}

/// Converts a [`crate::types::InputPersonalDocument`] into [`InputPersonalDocument`].
impl From<crate::types::InputPersonalDocument> for InputPersonalDocument {
    fn from(val: crate::types::InputPersonalDocument) -> Self {
        Self::InputPersonalDocument(Box::new(val))
    }
}

/// TDLib `InputThumbnail` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputThumbnail {
    /// A thumbnail to be sent along with a file; must be in JPEG or WEBP format for stickers, and less than 200 KB in size
    #[serde(rename(serialize = "inputThumbnail", deserialize = "inputThumbnail"))]
    InputThumbnail(Box<crate::types::InputThumbnail>),
}

impl InputThumbnail {
    /// Convenience constructor to create a [`InputThumbnail::InputThumbnail`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_thumbnail(val: crate::types::InputThumbnail) -> Self {
        Self::InputThumbnail(Box::new(val))
    }

}

/// Converts a [`crate::types::InputThumbnail`] into [`InputThumbnail`].
impl From<crate::types::InputThumbnail> for InputThumbnail {
    fn from(val: crate::types::InputThumbnail) -> Self {
        Self::InputThumbnail(Box::new(val))
    }
}

/// TDLib `InputAnimation` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputAnimation {
    /// An animation to be sent
    #[serde(rename(serialize = "inputAnimation", deserialize = "inputAnimation"))]
    InputAnimation(Box<crate::types::InputAnimation>),
}

impl InputAnimation {
    /// Convenience constructor to create a [`InputAnimation::InputAnimation`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_animation(val: crate::types::InputAnimation) -> Self {
        Self::InputAnimation(Box::new(val))
    }

}

/// Converts a [`crate::types::InputAnimation`] into [`InputAnimation`].
impl From<crate::types::InputAnimation> for InputAnimation {
    fn from(val: crate::types::InputAnimation) -> Self {
        Self::InputAnimation(Box::new(val))
    }
}

/// TDLib `InputAudio` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputAudio {
    /// An audio to be sent
    #[serde(rename(serialize = "inputAudio", deserialize = "inputAudio"))]
    InputAudio(Box<crate::types::InputAudio>),
}

impl InputAudio {
    /// Convenience constructor to create a [`InputAudio::InputAudio`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_audio(val: crate::types::InputAudio) -> Self {
        Self::InputAudio(Box::new(val))
    }

}

/// Converts a [`crate::types::InputAudio`] into [`InputAudio`].
impl From<crate::types::InputAudio> for InputAudio {
    fn from(val: crate::types::InputAudio) -> Self {
        Self::InputAudio(Box::new(val))
    }
}

/// TDLib `InputDocument` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputDocument {
    /// A document (general file) to be sent
    #[serde(rename(serialize = "inputDocument", deserialize = "inputDocument"))]
    InputDocument(Box<crate::types::InputDocument>),
}

impl InputDocument {
    /// Convenience constructor to create a [`InputDocument::InputDocument`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_document(val: crate::types::InputDocument) -> Self {
        Self::InputDocument(Box::new(val))
    }

}

/// Converts a [`crate::types::InputDocument`] into [`InputDocument`].
impl From<crate::types::InputDocument> for InputDocument {
    fn from(val: crate::types::InputDocument) -> Self {
        Self::InputDocument(Box::new(val))
    }
}

/// TDLib `InputPhoto` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputPhoto {
    /// A photo to be sent
    #[serde(rename(serialize = "inputPhoto", deserialize = "inputPhoto"))]
    InputPhoto(Box<crate::types::InputPhoto>),
}

impl InputPhoto {
    /// Convenience constructor to create a [`InputPhoto::InputPhoto`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_photo(val: crate::types::InputPhoto) -> Self {
        Self::InputPhoto(Box::new(val))
    }

}

/// Converts a [`crate::types::InputPhoto`] into [`InputPhoto`].
impl From<crate::types::InputPhoto> for InputPhoto {
    fn from(val: crate::types::InputPhoto) -> Self {
        Self::InputPhoto(Box::new(val))
    }
}

/// TDLib `InputVideo` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputVideo {
    /// A video to be sent
    #[serde(rename(serialize = "inputVideo", deserialize = "inputVideo"))]
    InputVideo(Box<crate::types::InputVideo>),
}

impl InputVideo {
    /// Convenience constructor to create a [`InputVideo::InputVideo`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_video(val: crate::types::InputVideo) -> Self {
        Self::InputVideo(Box::new(val))
    }

}

/// Converts a [`crate::types::InputVideo`] into [`InputVideo`].
impl From<crate::types::InputVideo> for InputVideo {
    fn from(val: crate::types::InputVideo) -> Self {
        Self::InputVideo(Box::new(val))
    }
}

/// TDLib `InputVideoNote` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputVideoNote {
    /// A video note to be sent
    #[serde(rename(serialize = "inputVideoNote", deserialize = "inputVideoNote"))]
    InputVideoNote(Box<crate::types::InputVideoNote>),
}

impl InputVideoNote {
    /// Convenience constructor to create a [`InputVideoNote::InputVideoNote`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn input_video_note(val: crate::types::InputVideoNote) -> Self {
        Self::InputVideoNote(Box::new(val))
    }

}

/// Converts a [`crate::types::InputVideoNote`] into [`InputVideoNote`].
impl From<crate::types::InputVideoNote> for InputVideoNote {
    fn from(val: crate::types::InputVideoNote) -> Self {
        Self::InputVideoNote(Box::new(val))
    }
}

/// TDLib `Animations` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum Animations {
    /// Represents a list of animations
    #[serde(rename(serialize = "animations", deserialize = "animations"))]
    Animations(Box<crate::types::Animations>),
}

impl Animations {
    /// Convenience constructor to create a [`Animations::Animations`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn animations(val: crate::types::Animations) -> Self {
        Self::Animations(Box::new(val))
    }

}

/// Converts a [`crate::types::Animations`] into [`Animations`].
impl From<crate::types::Animations> for Animations {
    fn from(val: crate::types::Animations) -> Self {
        Self::Animations(Box::new(val))
    }
}

/// Contains information about a file with messages exported from another app
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum MessageFileType {
    /// The messages were exported from a private chat
    #[serde(rename(serialize = "messageFileTypePrivate", deserialize = "messageFileTypePrivate"))]
    Private(Box<crate::types::MessageFileTypePrivate>),
    /// The messages were exported from a group chat
    #[serde(rename(serialize = "messageFileTypeGroup", deserialize = "messageFileTypeGroup"))]
    Group(Box<crate::types::MessageFileTypeGroup>),
    /// The messages were exported from a chat of unknown type
    #[serde(rename(serialize = "messageFileTypeUnknown", deserialize = "messageFileTypeUnknown"))]
    Unknown,
}

impl MessageFileType {
    /// Convenience constructor to create a [`MessageFileType::Private`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn private(val: crate::types::MessageFileTypePrivate) -> Self {
        Self::Private(Box::new(val))
    }

    /// Convenience constructor to create a [`MessageFileType::Group`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn group(val: crate::types::MessageFileTypeGroup) -> Self {
        Self::Group(Box::new(val))
    }

}

/// Converts a [`crate::types::MessageFileTypePrivate`] into [`MessageFileType`].
impl From<crate::types::MessageFileTypePrivate> for MessageFileType {
    fn from(val: crate::types::MessageFileTypePrivate) -> Self {
        Self::Private(Box::new(val))
    }
}

/// Converts a [`crate::types::MessageFileTypeGroup`] into [`MessageFileType`].
impl From<crate::types::MessageFileTypeGroup> for MessageFileType {
    fn from(val: crate::types::MessageFileTypeGroup) -> Self {
        Self::Group(Box::new(val))
    }
}

/// Represents the type of file
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum FileType {
    /// The data is not a file
    #[serde(rename(serialize = "fileTypeNone", deserialize = "fileTypeNone"))]
    None,
    /// The file is an animation
    #[serde(rename(serialize = "fileTypeAnimation", deserialize = "fileTypeAnimation"))]
    Animation,
    /// The file is an audio file
    #[serde(rename(serialize = "fileTypeAudio", deserialize = "fileTypeAudio"))]
    Audio,
    /// The file is a document
    #[serde(rename(serialize = "fileTypeDocument", deserialize = "fileTypeDocument"))]
    Document,
    /// The file is a video for a live photo
    #[serde(rename(serialize = "fileTypeLivePhotoVideo", deserialize = "fileTypeLivePhotoVideo"))]
    LivePhotoVideo,
    /// The file is a notification sound
    #[serde(rename(serialize = "fileTypeNotificationSound", deserialize = "fileTypeNotificationSound"))]
    NotificationSound,
    /// The file is a photo
    #[serde(rename(serialize = "fileTypePhoto", deserialize = "fileTypePhoto"))]
    Photo,
    /// The file is a photo published as a story
    #[serde(rename(serialize = "fileTypePhotoStory", deserialize = "fileTypePhotoStory"))]
    PhotoStory,
    /// The file is a profile photo
    #[serde(rename(serialize = "fileTypeProfilePhoto", deserialize = "fileTypeProfilePhoto"))]
    ProfilePhoto,
    /// The file was sent to a secret chat (the file type is not known to the server)
    #[serde(rename(serialize = "fileTypeSecret", deserialize = "fileTypeSecret"))]
    Secret,
    /// The file is a thumbnail of a file from a secret chat
    #[serde(rename(serialize = "fileTypeSecretThumbnail", deserialize = "fileTypeSecretThumbnail"))]
    SecretThumbnail,
    /// The file is a file from Secure storage used for storing Telegram Passport files
    #[serde(rename(serialize = "fileTypeSecure", deserialize = "fileTypeSecure"))]
    Secure,
    /// The file is a self-destructing video for a live photo in a private chat
    #[serde(rename(serialize = "fileTypeSelfDestructingLivePhotoVideo", deserialize = "fileTypeSelfDestructingLivePhotoVideo"))]
    SelfDestructingLivePhotoVideo,
    /// The file is a self-destructing photo in a private chat
    #[serde(rename(serialize = "fileTypeSelfDestructingPhoto", deserialize = "fileTypeSelfDestructingPhoto"))]
    SelfDestructingPhoto,
    /// The file is a self-destructing video in a private chat
    #[serde(rename(serialize = "fileTypeSelfDestructingVideo", deserialize = "fileTypeSelfDestructingVideo"))]
    SelfDestructingVideo,
    /// The file is a self-destructing video note in a private chat
    #[serde(rename(serialize = "fileTypeSelfDestructingVideoNote", deserialize = "fileTypeSelfDestructingVideoNote"))]
    SelfDestructingVideoNote,
    /// The file is a self-destructing voice note in a private chat
    #[serde(rename(serialize = "fileTypeSelfDestructingVoiceNote", deserialize = "fileTypeSelfDestructingVoiceNote"))]
    SelfDestructingVoiceNote,
    /// The file is a sticker
    #[serde(rename(serialize = "fileTypeSticker", deserialize = "fileTypeSticker"))]
    Sticker,
    /// The file is a thumbnail of another file
    #[serde(rename(serialize = "fileTypeThumbnail", deserialize = "fileTypeThumbnail"))]
    Thumbnail,
    /// The file type is not yet known
    #[serde(rename(serialize = "fileTypeUnknown", deserialize = "fileTypeUnknown"))]
    Unknown,
    /// The file is a video
    #[serde(rename(serialize = "fileTypeVideo", deserialize = "fileTypeVideo"))]
    Video,
    /// The file is a video note
    #[serde(rename(serialize = "fileTypeVideoNote", deserialize = "fileTypeVideoNote"))]
    VideoNote,
    /// The file is a video published as a story
    #[serde(rename(serialize = "fileTypeVideoStory", deserialize = "fileTypeVideoStory"))]
    VideoStory,
    /// The file is a voice note
    #[serde(rename(serialize = "fileTypeVoiceNote", deserialize = "fileTypeVoiceNote"))]
    VoiceNote,
    /// The file is a wallpaper or a background pattern
    #[serde(rename(serialize = "fileTypeWallpaper", deserialize = "fileTypeWallpaper"))]
    Wallpaper,
}

/// TDLib `StorageStatisticsByFileType` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum StorageStatisticsByFileType {
    /// Contains the storage usage statistics for a specific file type
    #[serde(rename(serialize = "storageStatisticsByFileType", deserialize = "storageStatisticsByFileType"))]
    StorageStatisticsByFileType(Box<crate::types::StorageStatisticsByFileType>),
}

impl StorageStatisticsByFileType {
    /// Convenience constructor to create a [`StorageStatisticsByFileType::StorageStatisticsByFileType`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn storage_statistics_by_file_type(val: crate::types::StorageStatisticsByFileType) -> Self {
        Self::StorageStatisticsByFileType(Box::new(val))
    }

}

/// Converts a [`crate::types::StorageStatisticsByFileType`] into [`StorageStatisticsByFileType`].
impl From<crate::types::StorageStatisticsByFileType> for StorageStatisticsByFileType {
    fn from(val: crate::types::StorageStatisticsByFileType) -> Self {
        Self::StorageStatisticsByFileType(Box::new(val))
    }
}

/// TDLib `FileDownloadedPrefixSize` union enum.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum FileDownloadedPrefixSize {
    /// Contains size of downloaded prefix of a file
    #[serde(rename(serialize = "fileDownloadedPrefixSize", deserialize = "fileDownloadedPrefixSize"))]
    FileDownloadedPrefixSize(Box<crate::types::FileDownloadedPrefixSize>),
}

impl FileDownloadedPrefixSize {
    /// Convenience constructor to create a [`FileDownloadedPrefixSize::FileDownloadedPrefixSize`] variant.
    ///
    /// Automatically wraps the payload in `Box`.
    pub fn file_downloaded_prefix_size(val: crate::types::FileDownloadedPrefixSize) -> Self {
        Self::FileDownloadedPrefixSize(Box::new(val))
    }

}

/// Converts a [`crate::types::FileDownloadedPrefixSize`] into [`FileDownloadedPrefixSize`].
impl From<crate::types::FileDownloadedPrefixSize> for FileDownloadedPrefixSize {
    fn from(val: crate::types::FileDownloadedPrefixSize) -> Self {
        Self::FileDownloadedPrefixSize(Box::new(val))
    }
}

