#[allow(clippy::all)]
use serde::{Deserialize, Serialize};


#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum InputFile {
    /// A file defined by its unique identifier
    #[serde(rename(serialize = "inputFileId", deserialize = "inputFileId"))]
    Id(crate::types::InputFileId),
    /// A file defined by its remote identifier. The remote identifier is guaranteed to be usable only if the corresponding file is still accessible to the user and known to TDLib.
    /// For example, if the file is from a message, then the message must be not deleted and accessible to the user. If the file database is disabled, then the corresponding object with the file must be preloaded by the application
    #[serde(rename(serialize = "inputFileRemote", deserialize = "inputFileRemote"))]
    Remote(crate::types::InputFileRemote),
    /// A file defined by a local path
    #[serde(rename(serialize = "inputFileLocal", deserialize = "inputFileLocal"))]
    Local(crate::types::InputFileLocal),
    /// A file generated by the application. The application must handle updates updateFileGenerationStart and updateFileGenerationStop to generate the file when asked by TDLib
    #[serde(rename(serialize = "inputFileGenerated", deserialize = "inputFileGenerated"))]
    Generated(crate::types::InputFileGenerated),
}
