#[allow(clippy::all)]
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "@type")]
pub enum MessageContent {
    /// A text message
    #[serde(rename(serialize = "messageText", deserialize = "messageText"))]
    MessageText(crate::types::MessageText),
    /// An animation message (GIF-style).
    #[serde(rename(serialize = "messageAnimation", deserialize = "messageAnimation"))]
    MessageAnimation(crate::types::MessageAnimation),
    /// An audio message
    #[serde(rename(serialize = "messageAudio", deserialize = "messageAudio"))]
    MessageAudio(crate::types::MessageAudio),
    /// A document message (general file)
    #[serde(rename(serialize = "messageDocument", deserialize = "messageDocument"))]
    MessageDocument(crate::types::MessageDocument),
    /// A message with paid media
    #[serde(rename(serialize = "messagePaidMedia", deserialize = "messagePaidMedia"))]
    MessagePaidMedia(crate::types::MessagePaidMedia),
    /// A photo message
    #[serde(rename(serialize = "messagePhoto", deserialize = "messagePhoto"))]
    MessagePhoto(crate::types::MessagePhoto),
    /// A sticker message
    #[serde(rename(serialize = "messageSticker", deserialize = "messageSticker"))]
    MessageSticker(crate::types::MessageSticker),
    /// A video message
    #[serde(rename(serialize = "messageVideo", deserialize = "messageVideo"))]
    MessageVideo(crate::types::MessageVideo),
    /// A video note message
    #[serde(rename(serialize = "messageVideoNote", deserialize = "messageVideoNote"))]
    MessageVideoNote(crate::types::MessageVideoNote),
    /// A voice note message
    #[serde(rename(serialize = "messageVoiceNote", deserialize = "messageVoiceNote"))]
    MessageVoiceNote(crate::types::MessageVoiceNote),
    /// A self-destructed photo message
    #[serde(rename(serialize = "messageExpiredPhoto", deserialize = "messageExpiredPhoto"))]
    MessageExpiredPhoto,
    /// A self-destructed video message
    #[serde(rename(serialize = "messageExpiredVideo", deserialize = "messageExpiredVideo"))]
    MessageExpiredVideo,
    /// A self-destructed video note message
    #[serde(rename(
        serialize = "messageExpiredVideoNote",
        deserialize = "messageExpiredVideoNote"
    ))]
    MessageExpiredVideoNote,
    /// A self-destructed voice note message
    #[serde(rename(
        serialize = "messageExpiredVoiceNote",
        deserialize = "messageExpiredVoiceNote"
    ))]
    MessageExpiredVoiceNote,
    /// A message with a location
    #[serde(rename(serialize = "messageLocation", deserialize = "messageLocation"))]
    MessageLocation(crate::types::MessageLocation),
    /// A message with information about a venue
    #[serde(rename(serialize = "messageVenue", deserialize = "messageVenue"))]
    MessageVenue(crate::types::MessageVenue),
    /// A message with a user contact
    #[serde(rename(serialize = "messageContact", deserialize = "messageContact"))]
    MessageContact(crate::types::MessageContact),
    /// A message with an animated emoji
    #[serde(rename(
        serialize = "messageAnimatedEmoji",
        deserialize = "messageAnimatedEmoji"
    ))]
    MessageAnimatedEmoji(crate::types::MessageAnimatedEmoji),
    /// A dice message. The dice value is randomly generated by the server
    #[serde(rename(serialize = "messageDice", deserialize = "messageDice"))]
    MessageDice(crate::types::MessageDice),
    /// A message with a game
    #[serde(rename(serialize = "messageGame", deserialize = "messageGame"))]
    MessageGame(crate::types::MessageGame),
    /// A message with a poll
    #[serde(rename(serialize = "messagePoll", deserialize = "messagePoll"))]
    MessagePoll(crate::types::MessagePoll),
    /// A stake dice message. The dice value is randomly generated by the server
    #[serde(rename(serialize = "messageStakeDice", deserialize = "messageStakeDice"))]
    MessageStakeDice(crate::types::MessageStakeDice),
    /// A message with a forwarded story
    #[serde(rename(serialize = "messageStory", deserialize = "messageStory"))]
    MessageStory(crate::types::MessageStory),
    /// A message with a checklist
    #[serde(rename(serialize = "messageChecklist", deserialize = "messageChecklist"))]
    MessageChecklist(crate::types::MessageChecklist),
    /// A message with an invoice from a bot. Use getInternalLink with internalLinkTypeBotStart to share the invoice
    #[serde(rename(serialize = "messageInvoice", deserialize = "messageInvoice"))]
    MessageInvoice(crate::types::MessageInvoice),
    /// A message with information about an ended call
    #[serde(rename(serialize = "messageCall", deserialize = "messageCall"))]
    MessageCall(crate::types::MessageCall),
    /// A message with information about a group call not bound to a chat. If the message is incoming, the call isn't active, isn't missed, and has no duration,
    /// and getOption("can_accept_calls") is true, then incoming call screen must be shown to the user. Use getGroupCallParticipants to show current group call participants on the screen.
    /// Use joinGroupCall to accept the call or declineGroupCallInvitation to decline it. If the call become active or missed, then the call screen must be hidden
    #[serde(rename(serialize = "messageGroupCall", deserialize = "messageGroupCall"))]
    MessageGroupCall(crate::types::MessageGroupCall),
    /// A new video chat was scheduled
    #[serde(rename(
        serialize = "messageVideoChatScheduled",
        deserialize = "messageVideoChatScheduled"
    ))]
    MessageVideoChatScheduled(crate::types::MessageVideoChatScheduled),
    /// A newly created video chat
    #[serde(rename(
        serialize = "messageVideoChatStarted",
        deserialize = "messageVideoChatStarted"
    ))]
    MessageVideoChatStarted(crate::types::MessageVideoChatStarted),
    /// A message with information about an ended video chat
    #[serde(rename(
        serialize = "messageVideoChatEnded",
        deserialize = "messageVideoChatEnded"
    ))]
    MessageVideoChatEnded(crate::types::MessageVideoChatEnded),
    /// A message with information about an invitation to a video chat
    #[serde(rename(
        serialize = "messageInviteVideoChatParticipants",
        deserialize = "messageInviteVideoChatParticipants"
    ))]
    MessageInviteVideoChatParticipants(crate::types::MessageInviteVideoChatParticipants),
    /// A newly created basic group
    #[serde(rename(
        serialize = "messageBasicGroupChatCreate",
        deserialize = "messageBasicGroupChatCreate"
    ))]
    MessageBasicGroupChatCreate(crate::types::MessageBasicGroupChatCreate),
    /// A newly created supergroup or channel
    #[serde(rename(
        serialize = "messageSupergroupChatCreate",
        deserialize = "messageSupergroupChatCreate"
    ))]
    MessageSupergroupChatCreate(crate::types::MessageSupergroupChatCreate),
    /// An updated chat title
    #[serde(rename(
        serialize = "messageChatChangeTitle",
        deserialize = "messageChatChangeTitle"
    ))]
    MessageChatChangeTitle(crate::types::MessageChatChangeTitle),
    /// An updated chat photo
    #[serde(rename(
        serialize = "messageChatChangePhoto",
        deserialize = "messageChatChangePhoto"
    ))]
    MessageChatChangePhoto(crate::types::MessageChatChangePhoto),
    /// A deleted chat photo
    #[serde(rename(
        serialize = "messageChatDeletePhoto",
        deserialize = "messageChatDeletePhoto"
    ))]
    MessageChatDeletePhoto,
    /// The owner of the chat has left
    #[serde(rename(
        serialize = "messageChatOwnerLeft",
        deserialize = "messageChatOwnerLeft"
    ))]
    MessageChatOwnerLeft(crate::types::MessageChatOwnerLeft),
    /// The owner of the chat has changed
    #[serde(rename(
        serialize = "messageChatOwnerChanged",
        deserialize = "messageChatOwnerChanged"
    ))]
    MessageChatOwnerChanged(crate::types::MessageChatOwnerChanged),
    /// Chat has_protected_content setting was changed or request to change it was rejected
    #[serde(rename(
        serialize = "messageChatHasProtectedContentToggled",
        deserialize = "messageChatHasProtectedContentToggled"
    ))]
    MessageChatHasProtectedContentToggled(crate::types::MessageChatHasProtectedContentToggled),
    /// Chat has_protected_content setting was requested to be disabled
    #[serde(rename(
        serialize = "messageChatHasProtectedContentDisableRequested",
        deserialize = "messageChatHasProtectedContentDisableRequested"
    ))]
    MessageChatHasProtectedContentDisableRequested(
        crate::types::MessageChatHasProtectedContentDisableRequested,
    ),
    /// New chat members were added
    #[serde(rename(
        serialize = "messageChatAddMembers",
        deserialize = "messageChatAddMembers"
    ))]
    MessageChatAddMembers(crate::types::MessageChatAddMembers),
    /// A new member joined the chat via an invite link
    #[serde(rename(
        serialize = "messageChatJoinByLink",
        deserialize = "messageChatJoinByLink"
    ))]
    MessageChatJoinByLink,
    /// A new member was accepted to the chat by an administrator
    #[serde(rename(
        serialize = "messageChatJoinByRequest",
        deserialize = "messageChatJoinByRequest"
    ))]
    MessageChatJoinByRequest,
    /// A chat member was deleted
    #[serde(rename(
        serialize = "messageChatDeleteMember",
        deserialize = "messageChatDeleteMember"
    ))]
    MessageChatDeleteMember(crate::types::MessageChatDeleteMember),
    /// A basic group was upgraded to a supergroup and was deactivated as the result
    #[serde(rename(
        serialize = "messageChatUpgradeTo",
        deserialize = "messageChatUpgradeTo"
    ))]
    MessageChatUpgradeTo(crate::types::MessageChatUpgradeTo),
    /// A supergroup has been created from a basic group
    #[serde(rename(
        serialize = "messageChatUpgradeFrom",
        deserialize = "messageChatUpgradeFrom"
    ))]
    MessageChatUpgradeFrom(crate::types::MessageChatUpgradeFrom),
    /// A message has been pinned
    #[serde(rename(serialize = "messagePinMessage", deserialize = "messagePinMessage"))]
    MessagePinMessage(crate::types::MessagePinMessage),
    /// A screenshot of a message in the chat has been taken
    #[serde(rename(
        serialize = "messageScreenshotTaken",
        deserialize = "messageScreenshotTaken"
    ))]
    MessageScreenshotTaken,
    /// A new background was set in the chat
    #[serde(rename(
        serialize = "messageChatSetBackground",
        deserialize = "messageChatSetBackground"
    ))]
    MessageChatSetBackground(crate::types::MessageChatSetBackground),
    /// A theme in the chat has been changed
    #[serde(rename(serialize = "messageChatSetTheme", deserialize = "messageChatSetTheme"))]
    MessageChatSetTheme(crate::types::MessageChatSetTheme),
    /// The auto-delete or self-destruct timer for messages in the chat has been changed
    #[serde(rename(
        serialize = "messageChatSetMessageAutoDeleteTime",
        deserialize = "messageChatSetMessageAutoDeleteTime"
    ))]
    MessageChatSetMessageAutoDeleteTime(crate::types::MessageChatSetMessageAutoDeleteTime),
    /// The chat was boosted by the sender of the message
    #[serde(rename(serialize = "messageChatBoost", deserialize = "messageChatBoost"))]
    MessageChatBoost(crate::types::MessageChatBoost),
    /// A forum topic has been created
    #[serde(rename(
        serialize = "messageForumTopicCreated",
        deserialize = "messageForumTopicCreated"
    ))]
    MessageForumTopicCreated(crate::types::MessageForumTopicCreated),
    /// A forum topic has been edited
    #[serde(rename(
        serialize = "messageForumTopicEdited",
        deserialize = "messageForumTopicEdited"
    ))]
    MessageForumTopicEdited(crate::types::MessageForumTopicEdited),
    /// A forum topic has been closed or opened
    #[serde(rename(
        serialize = "messageForumTopicIsClosedToggled",
        deserialize = "messageForumTopicIsClosedToggled"
    ))]
    MessageForumTopicIsClosedToggled(crate::types::MessageForumTopicIsClosedToggled),
    /// A General forum topic has been hidden or unhidden
    #[serde(rename(
        serialize = "messageForumTopicIsHiddenToggled",
        deserialize = "messageForumTopicIsHiddenToggled"
    ))]
    MessageForumTopicIsHiddenToggled(crate::types::MessageForumTopicIsHiddenToggled),
    /// A profile photo was suggested to a user in a private chat
    #[serde(rename(
        serialize = "messageSuggestProfilePhoto",
        deserialize = "messageSuggestProfilePhoto"
    ))]
    MessageSuggestProfilePhoto(crate::types::MessageSuggestProfilePhoto),
    /// A birthdate was suggested to be set
    #[serde(rename(
        serialize = "messageSuggestBirthdate",
        deserialize = "messageSuggestBirthdate"
    ))]
    MessageSuggestBirthdate(crate::types::MessageSuggestBirthdate),
    /// A non-standard action has happened in the chat
    #[serde(rename(
        serialize = "messageCustomServiceAction",
        deserialize = "messageCustomServiceAction"
    ))]
    MessageCustomServiceAction(crate::types::MessageCustomServiceAction),
    /// A new high score was achieved in a game
    #[serde(rename(serialize = "messageGameScore", deserialize = "messageGameScore"))]
    MessageGameScore(crate::types::MessageGameScore),
    /// A payment has been sent to a bot or a business account
    #[serde(rename(
        serialize = "messagePaymentSuccessful",
        deserialize = "messagePaymentSuccessful"
    ))]
    MessagePaymentSuccessful(crate::types::MessagePaymentSuccessful),
    /// A payment has been received by the bot or the business account
    #[serde(rename(
        serialize = "messagePaymentSuccessfulBot",
        deserialize = "messagePaymentSuccessfulBot"
    ))]
    MessagePaymentSuccessfulBot(crate::types::MessagePaymentSuccessfulBot),
    /// A payment has been refunded
    #[serde(rename(
        serialize = "messagePaymentRefunded",
        deserialize = "messagePaymentRefunded"
    ))]
    MessagePaymentRefunded(crate::types::MessagePaymentRefunded),
    /// Telegram Premium was gifted to a user
    #[serde(rename(
        serialize = "messageGiftedPremium",
        deserialize = "messageGiftedPremium"
    ))]
    MessageGiftedPremium(crate::types::MessageGiftedPremium),
    /// A Telegram Premium gift code was created for the user
    #[serde(rename(
        serialize = "messagePremiumGiftCode",
        deserialize = "messagePremiumGiftCode"
    ))]
    MessagePremiumGiftCode(crate::types::MessagePremiumGiftCode),
    /// A giveaway was created for the chat. Use telegramPaymentPurposePremiumGiveaway, storePaymentPurposePremiumGiveaway, telegramPaymentPurposeStarGiveaway, or storePaymentPurposeStarGiveaway to create a giveaway
    #[serde(rename(
        serialize = "messageGiveawayCreated",
        deserialize = "messageGiveawayCreated"
    ))]
    MessageGiveawayCreated(crate::types::MessageGiveawayCreated),
    /// A giveaway
    #[serde(rename(serialize = "messageGiveaway", deserialize = "messageGiveaway"))]
    MessageGiveaway(crate::types::MessageGiveaway),
    /// A giveaway without public winners has been completed for the chat
    #[serde(rename(
        serialize = "messageGiveawayCompleted",
        deserialize = "messageGiveawayCompleted"
    ))]
    MessageGiveawayCompleted(crate::types::MessageGiveawayCompleted),
    /// A giveaway with public winners has been completed for the chat
    #[serde(rename(
        serialize = "messageGiveawayWinners",
        deserialize = "messageGiveawayWinners"
    ))]
    MessageGiveawayWinners(crate::types::MessageGiveawayWinners),
    /// Telegram Stars were gifted to a user
    #[serde(rename(serialize = "messageGiftedStars", deserialize = "messageGiftedStars"))]
    MessageGiftedStars(crate::types::MessageGiftedStars),
    /// Toncoins were gifted to a user
    #[serde(rename(serialize = "messageGiftedTon", deserialize = "messageGiftedTon"))]
    MessageGiftedTon(crate::types::MessageGiftedTon),
    /// A Telegram Stars were received by the current user from a giveaway
    #[serde(rename(
        serialize = "messageGiveawayPrizeStars",
        deserialize = "messageGiveawayPrizeStars"
    ))]
    MessageGiveawayPrizeStars(crate::types::MessageGiveawayPrizeStars),
    /// A regular gift was received or sent by the current user, or the current user was notified about a channel gift
    #[serde(rename(serialize = "messageGift", deserialize = "messageGift"))]
    MessageGift(crate::types::MessageGift),
    /// An upgraded gift was received or sent by the current user, or the current user was notified about a channel gift
    #[serde(rename(serialize = "messageUpgradedGift", deserialize = "messageUpgradedGift"))]
    MessageUpgradedGift(crate::types::MessageUpgradedGift),
    /// A gift which purchase, upgrade or transfer were refunded
    #[serde(rename(
        serialize = "messageRefundedUpgradedGift",
        deserialize = "messageRefundedUpgradedGift"
    ))]
    MessageRefundedUpgradedGift(crate::types::MessageRefundedUpgradedGift),
    /// An offer to purchase an upgraded gift was sent or received
    #[serde(rename(
        serialize = "messageUpgradedGiftPurchaseOffer",
        deserialize = "messageUpgradedGiftPurchaseOffer"
    ))]
    MessageUpgradedGiftPurchaseOffer(crate::types::MessageUpgradedGiftPurchaseOffer),
    /// An offer to purchase a gift was rejected or expired
    #[serde(rename(
        serialize = "messageUpgradedGiftPurchaseOfferRejected",
        deserialize = "messageUpgradedGiftPurchaseOfferRejected"
    ))]
    MessageUpgradedGiftPurchaseOfferRejected(
        crate::types::MessageUpgradedGiftPurchaseOfferRejected,
    ),
    /// Paid messages were refunded
    #[serde(rename(
        serialize = "messagePaidMessagesRefunded",
        deserialize = "messagePaidMessagesRefunded"
    ))]
    MessagePaidMessagesRefunded(crate::types::MessagePaidMessagesRefunded),
    /// A price for paid messages was changed in the supergroup chat
    #[serde(rename(
        serialize = "messagePaidMessagePriceChanged",
        deserialize = "messagePaidMessagePriceChanged"
    ))]
    MessagePaidMessagePriceChanged(crate::types::MessagePaidMessagePriceChanged),
    /// A price for direct messages was changed in the channel chat
    #[serde(rename(
        serialize = "messageDirectMessagePriceChanged",
        deserialize = "messageDirectMessagePriceChanged"
    ))]
    MessageDirectMessagePriceChanged(crate::types::MessageDirectMessagePriceChanged),
    /// Some tasks from a checklist were marked as done or not done
    #[serde(rename(
        serialize = "messageChecklistTasksDone",
        deserialize = "messageChecklistTasksDone"
    ))]
    MessageChecklistTasksDone(crate::types::MessageChecklistTasksDone),
    /// Some tasks were added to a checklist
    #[serde(rename(
        serialize = "messageChecklistTasksAdded",
        deserialize = "messageChecklistTasksAdded"
    ))]
    MessageChecklistTasksAdded(crate::types::MessageChecklistTasksAdded),
    /// Approval of suggested post has failed, because the user which proposed the post had no enough funds
    #[serde(rename(
        serialize = "messageSuggestedPostApprovalFailed",
        deserialize = "messageSuggestedPostApprovalFailed"
    ))]
    MessageSuggestedPostApprovalFailed(crate::types::MessageSuggestedPostApprovalFailed),
    /// A suggested post was approved
    #[serde(rename(
        serialize = "messageSuggestedPostApproved",
        deserialize = "messageSuggestedPostApproved"
    ))]
    MessageSuggestedPostApproved(crate::types::MessageSuggestedPostApproved),
    /// A suggested post was declined
    #[serde(rename(
        serialize = "messageSuggestedPostDeclined",
        deserialize = "messageSuggestedPostDeclined"
    ))]
    MessageSuggestedPostDeclined(crate::types::MessageSuggestedPostDeclined),
    /// A suggested post was published for getOption("suggested_post_lifetime_min") seconds and payment for the post was received
    #[serde(rename(
        serialize = "messageSuggestedPostPaid",
        deserialize = "messageSuggestedPostPaid"
    ))]
    MessageSuggestedPostPaid(crate::types::MessageSuggestedPostPaid),
    /// A suggested post was refunded
    #[serde(rename(
        serialize = "messageSuggestedPostRefunded",
        deserialize = "messageSuggestedPostRefunded"
    ))]
    MessageSuggestedPostRefunded(crate::types::MessageSuggestedPostRefunded),
    /// A contact has registered with Telegram
    #[serde(rename(
        serialize = "messageContactRegistered",
        deserialize = "messageContactRegistered"
    ))]
    MessageContactRegistered,
    /// The current user shared users, which were requested by the bot
    #[serde(rename(serialize = "messageUsersShared", deserialize = "messageUsersShared"))]
    MessageUsersShared(crate::types::MessageUsersShared),
    /// The current user shared a chat, which was requested by the bot
    #[serde(rename(serialize = "messageChatShared", deserialize = "messageChatShared"))]
    MessageChatShared(crate::types::MessageChatShared),
    /// The user allowed the bot to send messages
    #[serde(rename(
        serialize = "messageBotWriteAccessAllowed",
        deserialize = "messageBotWriteAccessAllowed"
    ))]
    MessageBotWriteAccessAllowed(crate::types::MessageBotWriteAccessAllowed),
    /// Data from a Web App has been sent to a bot
    #[serde(rename(
        serialize = "messageWebAppDataSent",
        deserialize = "messageWebAppDataSent"
    ))]
    MessageWebAppDataSent(crate::types::MessageWebAppDataSent),
    /// Telegram Passport data has been sent to a bot
    #[serde(rename(
        serialize = "messagePassportDataSent",
        deserialize = "messagePassportDataSent"
    ))]
    MessagePassportDataSent(crate::types::MessagePassportDataSent),
    /// A user in the chat came within proximity alert range
    #[serde(rename(
        serialize = "messageProximityAlertTriggered",
        deserialize = "messageProximityAlertTriggered"
    ))]
    MessageProximityAlertTriggered(crate::types::MessageProximityAlertTriggered),
    /// A message content that is not supported in the current TDLib version
    #[serde(rename(serialize = "messageUnsupported", deserialize = "messageUnsupported"))]
    MessageUnsupported,
}
