use sea_orm::ConnectionTrait;
use sea_orm::sea_query::{ColumnDef, ForeignKeyAction, ForeignKeyCreateStatement, Index, Table};

use super::exec_schema_statement;

pub(super) async fn create<C>(db: &C) -> anyhow::Result<()>
where
    C: ConnectionTrait,
{
    exec_schema_statement(
        db,
        Table::create()
            .table("transfer_job")
            .if_not_exists()
            .col(
                ColumnDef::new("id")
                    .big_integer()
                    .not_null()
                    .auto_increment()
                    .primary_key(),
            )
            .col(ColumnDef::new("request_chat_id").big_integer().not_null())
            .col(
                ColumnDef::new("request_message_id")
                    .big_integer()
                    .not_null(),
            )
            .col(
                ColumnDef::new("owner_user_id")
                    .big_integer()
                    .not_null()
                    .default(0),
            )
            .col(ColumnDef::new("source_link").string().not_null())
            .col(
                ColumnDef::new("source_kind")
                    .string()
                    .not_null()
                    .default("link"),
            )
            .col(
                ColumnDef::new("source_client_role")
                    .string()
                    .not_null()
                    .default("user"),
            )
            .col(
                ColumnDef::new("allow_user_fallback")
                    .boolean()
                    .not_null()
                    .default(false),
            )
            .col(ColumnDef::new("source_chat_id").big_integer().not_null())
            .col(ColumnDef::new("source_message_id").big_integer().not_null())
            .col(
                ColumnDef::new("source_album_id")
                    .big_integer()
                    .not_null()
                    .default(0),
            )
            .col(ColumnDef::new("target_chat_id").big_integer().not_null())
            .col(ColumnDef::new("result_message_id").big_integer())
            .col(ColumnDef::new("result_message_link").string())
            .col(ColumnDef::new("status").string().not_null())
            .col(
                ColumnDef::new("total_items")
                    .integer()
                    .not_null()
                    .default(0),
            )
            .col(ColumnDef::new("done_items").integer().not_null().default(0))
            .col(
                ColumnDef::new("failed_items")
                    .integer()
                    .not_null()
                    .default(0),
            )
            .col(
                ColumnDef::new("retry_count")
                    .integer()
                    .not_null()
                    .default(0),
            )
            .col(
                ColumnDef::new("cost_points")
                    .big_integer()
                    .not_null()
                    .default(0),
            )
            .col(
                ColumnDef::new("charged_points")
                    .big_integer()
                    .not_null()
                    .default(0),
            )
            .col(
                ColumnDef::new("billing_status")
                    .string()
                    .not_null()
                    .default("free"),
            )
            .col(ColumnDef::new("last_error").string())
            .col(
                ColumnDef::new("created_at")
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .col(
                ColumnDef::new("updated_at")
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .col(ColumnDef::new("finished_at").timestamp_with_time_zone())
            .index(
                Index::create()
                    .name("transfer_job_request_uk")
                    .col("request_chat_id")
                    .col("request_message_id")
                    .unique(),
            )
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_job_status_updated_idx")
            .table("transfer_job")
            .col("status")
            .col("updated_at")
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_job_owner_status_updated_idx")
            .table("transfer_job")
            .col("owner_user_id")
            .col("status")
            .col("updated_at")
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_job_source_link_idx")
            .table("transfer_job")
            .col("source_link")
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_job_source_target_status_idx")
            .table("transfer_job")
            .col("source_link")
            .col("target_chat_id")
            .col("status")
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_job_success_lookup_idx")
            .table("transfer_job")
            .col("source_link")
            .col("target_chat_id")
            .col("status")
            .col("finished_at")
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Table::create()
            .table("transfer_item")
            .if_not_exists()
            .col(
                ColumnDef::new("id")
                    .big_integer()
                    .not_null()
                    .auto_increment()
                    .primary_key(),
            )
            .col(ColumnDef::new("job_id").big_integer().not_null())
            .col(ColumnDef::new("source_chat_id").big_integer().not_null())
            .col(ColumnDef::new("source_message_id").big_integer().not_null())
            .col(ColumnDef::new("file_key").string().not_null())
            .col(
                ColumnDef::new("file_owner_client_role")
                    .string()
                    .not_null()
                    .default("user"),
            )
            .col(ColumnDef::new("status").string().not_null())
            .col(
                ColumnDef::new("retry_count")
                    .integer()
                    .not_null()
                    .default(0),
            )
            .col(ColumnDef::new("error_message").string())
            .col(
                ColumnDef::new("file_ref_released")
                    .boolean()
                    .not_null()
                    .default(false),
            )
            .col(
                ColumnDef::new("created_at")
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .col(
                ColumnDef::new("updated_at")
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .foreign_key(
                ForeignKeyCreateStatement::new()
                    .name("transfer_item_job_fk")
                    .from_tbl("transfer_item")
                    .from_col("job_id")
                    .to_tbl("transfer_job")
                    .to_col("id")
                    .on_delete(ForeignKeyAction::Cascade)
                    .on_update(ForeignKeyAction::Cascade),
            )
            .index(
                Index::create()
                    .name("transfer_item_job_source_uk")
                    .col("job_id")
                    .col("source_chat_id")
                    .col("source_message_id")
                    .unique(),
            )
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_item_job_status_idx")
            .table("transfer_item")
            .col("job_id")
            .col("status")
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Table::create()
            .table("transfer_result_message")
            .if_not_exists()
            .col(
                ColumnDef::new("id")
                    .big_integer()
                    .not_null()
                    .auto_increment()
                    .primary_key(),
            )
            .col(ColumnDef::new("job_id").big_integer().not_null())
            .col(ColumnDef::new("result_index").integer().not_null())
            .col(ColumnDef::new("target_chat_id").big_integer().not_null())
            .col(ColumnDef::new("message_id").big_integer().not_null())
            .col(ColumnDef::new("message_link").string().not_null())
            .col(
                ColumnDef::new("is_album")
                    .boolean()
                    .not_null()
                    .default(false),
            )
            .col(ColumnDef::new("item_count").integer().not_null().default(1))
            .col(
                ColumnDef::new("created_at")
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .col(
                ColumnDef::new("updated_at")
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .foreign_key(
                ForeignKeyCreateStatement::new()
                    .name("transfer_result_message_job_fk")
                    .from_tbl("transfer_result_message")
                    .from_col("job_id")
                    .to_tbl("transfer_job")
                    .to_col("id")
                    .on_delete(ForeignKeyAction::Cascade)
                    .on_update(ForeignKeyAction::Cascade),
            )
            .index(
                Index::create()
                    .name("transfer_result_message_job_index_uk")
                    .col("job_id")
                    .col("result_index")
                    .unique(),
            )
            .to_owned(),
    )
    .await?;

    exec_schema_statement(
        db,
        Index::create()
            .if_not_exists()
            .name("transfer_result_message_job_idx")
            .table("transfer_result_message")
            .col("job_id")
            .col("result_index")
            .to_owned(),
    )
    .await?;

    Ok(())
}

pub(super) async fn drop<C>(db: &C) -> anyhow::Result<()>
where
    C: ConnectionTrait,
{
    exec_schema_statement(
        db,
        Table::drop()
            .table("transfer_result_message")
            .if_exists()
            .to_owned(),
    )
    .await?;
    exec_schema_statement(
        db,
        Table::drop().table("transfer_item").if_exists().to_owned(),
    )
    .await?;
    exec_schema_statement(
        db,
        Table::drop().table("transfer_job").if_exists().to_owned(),
    )
    .await?;
    Ok(())
}
